### ISSUE TITLE
Distinction visuelle entre champs de MD saisis et non saisis, en production

### ISSUE THREAD

**Issue by StormKlaus** [MTES-MCT/metadata-postgresql#100]
En production / édition, pourrait t-on voir les champs non saisis grisés par défaut (ou autre) afin d'identifier les champs saisis plus facilement lorsque l'on scroll / navigue dans le panneau... ?

(En consultation, seuls les champs saisis apparaissent et c'est parfait !)

**Comment by WREATCHED** [comment]
C'est une bonne idée, mais il faut que je regarde si mettre du grisé ou autre chose ne sature pas ou alourdisse visuellement l'ihm et produise un effet contraire.
J'imagine déjà mettre un effet visuel par défaut et donner la possibilité dans la boite de dialogue de personnalisation de l'interface de le modifier.
 - [x] Trouver un effet visuel par défaut;
 - [x] Implémenter dans l'application Plume
 - [x] Personnalisation de l'effet visuel dans la boite de dialogue de personnalisation

**Comment by StormKlaus** [comment]
Ce serait parfait :-)

**Comment by WREATCHED** [comment]
**Ma réponse en vidéo**
Des remarques et ou suggestions et avis

https://user-images.githubusercontent.com/66324136/208451105-32c59436-4e9d-4a2f-a6b6-5f27f6a2c84e.mp4

**Comment by StormKlaus** [comment]
Est-ce que le fond gris (ou bleu) pourrait disparaitre dès la saisi du champ de MD, sans passer par la sauvegarde ?

Ce serait un petit plus dont je peux me passer, l'essentiel est bien là.

Ce nouveau développement me satisfait amplement, encore merci !

**Comment by alhyss** [comment]
Vraiment sympa de pouvoir aussi gérer l'opacité. Et beau boulot pour la prise en charge sur tous les widgets de saisie !

Par contre : 
- Avec un gris assez foncé comme la couleur par défaut, je trouve que ça ressemble beaucoup (trop) à des zones désactivées, dans lesquelles l'utilisateur pourrait croire qu'il n'est pas censé écrire. Évidemment, chacun pourra choisir la teinte qu'il veut, mais j'aimerais bien qu'on optimise la couleur par défaut pour qu'elle ne soit pas source de confusion ou, si on n'arrive pas à quelque chose de complètement satisfaisant, qu'on ne mette rien par défaut.
- Même réflexion que @StormKlaus. Je trouverais cette fonctionnalité beaucoup plus satisfaisante s'il n'y avait pas besoin d'enregistrer pour que la zone redevienne blanche...

**Comment by WREATCHED** [comment]
@all Besoins de précisions
@alhyss Comme je l'ai indiqué, j'ai pris une couleur qui sera créée par défaut #cecece.
Vous pouvez jouer avec un éditeur de couler et me faire parvenir celle qui vous semblera la plus opportune.
@alhyss @StormKlaus 
j'y avais effectivement déjà réfléchi, mais je ne pensais pas que vous iriez jusque là mais pourquoi pas.
 - [x]  Changement de couleur en quittant le focus de chaque widget.
 - [x] Changement de couleur en tapant une lettre dans les zone de saisie et/ou choix d'un item dans une liste déroulante et/ou choix d'une date dans l'assistant.

Je n'ai pas fait de test, mais il y aura forcément un temps de latence, que je ne mesure pas tant que ce n'est pas fait et il faut que je l'implémente partout, donc pas mal de taf.

**Comment by alhyss** [comment]
Je regarderais bien ce que ça donne avec un gris légèrement plus clair que celui qui sert de teinte de base pour les widgets ? Mais ne t'embête pas trop. Ce n'est pas bloquant et je pourrai faire des essais moi-même, effectivement.

Je ne comprends pas trop ce que tu veux faire avec le changement de couleur en quittant le focus des widgets ? A priori, c'est au second point que je pensais, pour ma part.

Ceci étant dit, on parle d'un sujet qui me semble intéressant, mais qui est aussi très peu urgent. C'est une fonctionnalité post v1.0 qui me semble moins prioritaire que l'interface de gestion des modèles.

**Comment by WREATCHED** [comment]
@alhyss 
pour ``Je ne comprends pas trop ce que tu veux faire avec le changement de couleur en quittant le focus des widgets ? A priori, c'est au second point que je pensais, pour ma part.
``
Je t'appellerai, ça ira plus vite pour t'expliquer ce que je veux faire ou plutôt ce qu'il faut faire.

**Comment by WREATCHED** [comment]
**Ma seconde réponse en vidéo**
Des remarques et ou suggestions et avis

https://user-images.githubusercontent.com/66324136/208667981-5ab6c288-c3a9-4a3d-b826-ea665fdd641c.mp4

**Comment by StormKlaus** [comment]
Rien à redire, je trouve ça parfait !
MERCI

**Comment by alhyss** [comment]
Absolument d'accord, c'est super cool ! 🥳

**Comment by WREATCHED** [comment]
C'est mon cadeau de noël
![image](https://user-images.githubusercontent.com/66324136/208684302-4415b235-61d0-4bb5-97bf-76925a1bcbdc.png)

**Comment by WREATCHED** [comment]
Bjr,
Vu que le monsieur en rouge 
![image](https://user-images.githubusercontent.com/66324136/209152899-204eda0f-b25d-4519-97b1-0d96e5b2d50c.png)
n'est pas passé encore, vite un nouveau cadeau.
"Plume joue à cache-cache avec ses zone de saisies ......."

https://user-images.githubusercontent.com/66324136/209153085-1fb4581b-f182-4804-86b6-3516f97e8dce.mp4

**Comment by DDT-16** [comment]
Bonjour,
Bonne année à tous.
Cette fonctionnalité permet d'avoir un visuel rapide sur les zones non saisies et je trouve cette possibilité vraiment bien. On va directement aux zones à compléter. Le fait que l'option soit paramétrable est aussi un plus pour s'adapter aux goûts de chacun.

Merci.
