### ISSUE TITLE
Saisi du thème COVADIS - implémentation automatique ?

### ISSUE THREAD

**Issue by StormKlaus** [MTES-MCT/metadata-postgresql#104]
Pourrait on voir le thème COVADIS de retranscrit automatiquement en fonction de sa localisation dans tel ou tel schéma "c_" de PostgreSQL / PostGIS ?

D'ailleurs, on ne peut pas saisir le thème COVADIS il me semble... (pas de champs de MD correspondant ?)

**Comment by alhyss** [comment]
Pour ton second point, il sera prochainement possible de saisir les thèmes COVADIS dans le champ _Thèmes_. Ce sera un vocabulaire contrôlé supplémentaire, en plus des thèmes ISO, INSPIRE, etc. Je compte le faire à court terme, car il existe maintenant des URI pour représenter ce vocabulaire.

Le calcul automatique que tu évoques me semble être une bonne idée. Ce n'est pas une méthode de calcul tout à fait standard, par contre. Il faut trouver une manière propre de gérer la correspondance entre les termes du vocabulaire et les noms des schémas. On est plutôt sur du moyen terme.

**Comment by alhyss** [comment]
J'ai ajouté une [méthode de calcul](https://mtes-mct.github.io/metadata-postgresql/usage/metadonnees_calculees.html) pour la métadonnée *Thèmes* / `dcat:theme`. Comme la quasi totalité des méthodes de calcul, elle n'est pas active dans les modèles pré-configurés, il faut personnaliser les modèles pour s'en servir. Elle récupère les catégories correspondantes du vocabulaire *Thèmes (Ecosphères)* susmentionné pour les schémas de la nomenclature. Par défaut, elle prend les deux niveaux, mais il est possible de la configurer via le modèle pour ne récupérer que l'un ou l'autre.

@StormKlaus Est-ce que ça répond à ton besoin ?
