### ISSUE TITLE
Pas d'avertissement avant les actions qui réinitialisent la fiche de métadonnées après un import

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#105]
_Signalé par la DDT 16 le 15 décembre 2022._

Lorsque l'utilisateur importe des métadonnées INSPIRE ou DCAT et clique sur l'un des boutons de la barre d'outils qui réinitialise l'interface sans avoir fait aucune modification entre temps, l'avertissement sur le risque de perte d'informations non sauvegardées n'apparaît pas, ou du moins pas toujours.

Du point de vue de l'utilisateur, il devrait systématiquement s'afficher, car il y a bel et bien des modifications non enregistrées dans la fiche.

Exemples fournis par la DDT 16 : 
- Import de la fiche "Points de prélèvements associés aux stations de mesure de la qualité des eaux superficielles continentales (STQ) - France entière, donnée du Sandre" au format RDF téléchargée via l'export RDF depuis https://www.sandre.eaufrance.fr/atlas/srv/fre/catalog.search#/metadata/7668705b-154d-48b3-965c-f09c50716812 : l'alerte s'active si on change de mode sans sauvegarder.
- Pour le même jeu de données, avec un export de la fiche sous forme de fichier XML INSPIRE : l'alerte ne s'active pas si on change de mode sans sauvegarder.
- Pour le jeu de données "Plan d'eau de la Charente" catalogué dans Géo-IDE Catalogue (http://catalogue.geo-ide.developpement-durable.gouv.fr/catalogue/srv/fre/catalog.search#/metadata/fr-120066022-jdd-89a93ae4-18f8-425f-ac5c-c1cd6392ff31), l'alerte ne fonctionne pas après l'import de la fiche via _Import depuis un service CSW (INSPIRE)_.

**Comment by alhyss** [comment]
@WREATCHED Si tu as un peu de temps dans les jours qui viennent, je veux bien un peu d'aide pour comprendre pourquoi il y a des alertes après un import DCAT, car il semblerait que ce soit systématique ? En tout cas je reproduis ça avec le fichier de test [dcat_eurostat_bilan_nutritif_brut_terre_agricole.ttl](https://github.com/MTES-MCT/metadata-postgresql/blob/main/plume/rdf/tests/samples/dcat_eurostat_bilan_nutritif_brut_terre_agricole.ttl)... Pour autant que j'ai pu voir, l'attribut `WidgetsDict.modified` vaut `False`, mais est-ce que tu peux le confirmer de ton côté ? Et, si c'est parce qu'une valeur a été modifiée que le message apparaît, est-ce que tu pourrais me préciser laquelle ou lesquelles ?

**Comment by WREATCHED** [comment]
Hello,
Pour répondre à ta dernière question, je pense que c'est le bon cas d'usage

- J'ai importé les données;
- je change de modèle;
- même si il y a de nouvelles données qui s'affichent, je n'ai rien modifié et donc je conserve les données 
- issues de l'import

C'est ce que je pense de plus logique

**Comment by WREATCHED** [comment]
Oui, très bien

**Comment by WREATCHED** [comment]
Corrigé dans plume_ui.py
````
if self.mDicObjetsInstancies.modified or bibli_plume.ifChangeValues(self.mDicObjetsInstancies)  :
par
if self.mDicObjetsInstancies.modified or bibli_plume.ifChangeValues(self.mDicObjetsInstancies) or self.metagraph.rewritten :
````
Si ok on pourra clore

**Comment by alhyss** [comment]
Il faudra tout de même qu'on explique cette histoire-là soigneusement dans la doc. Par exemple, il n'est pas forcément évident en premier abord que lorsqu'on change de modèle immédiatement après un import on n'a pas d'avertissement parce que le résultat de l'import est conservé dans l'interface même s'il n'a pas été sauvegardé en base, tandis que si on a saisi une valeur dans l'intervalle, l'avertissement apparaît parce que cette modification-là va être perdue, le dictionnaire étant récréé avec les métadonnées dans leur état à l'issue de l'import...
