### ISSUE TITLE
Mise à jour des bibliothèques intégrées

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#108]
Notamment `wheel` et `setuptools`, qui ont fait l'objet de mises à jour suite à la découverte de failles de sécurité.

Cf. pull requests #106 et #107.

**Comment by WREATCHED** [comment]
https://pypi.org/project/setuptools/#history propose une version 65.6.5 et le Pull request une version 65.5.1
![image](https://user-images.githubusercontent.com/66324136/210557309-ed58b758-369f-46c2-8ba3-b7c792c4a50e.png)
Que fait-on ? je maintiens la 65.5.1 ou bien je mets la der version et change à la main le requirement.txt ?

**Comment by WREATCHED** [comment]
Idem pour le Wheel de 0.38.1 à 0.38.4.
Je propose de mettre les dernières maj pour les deux bibliothèques

**Comment by WREATCHED** [comment]
![image](https://user-images.githubusercontent.com/66324136/210559229-2cb5dfe0-b477-4e4d-bfdc-ca9562afc81e.png)

**Comment by WREATCHED** [comment]
Je viens de pousser la version 0.7.0 reprenant notamment la maj des bibliothèques

**Comment by alhyss** [comment]
@WREATCHED Absolument d'accord avec ton choix de mettre les dernières versions ! Les deux pull request ont été fermés automatiquement, donc c'est parfait.

Est-ce que tu en a profité pour vérifier les autres bibliothèques ?

**Comment by WREATCHED** [comment]
Oui, j'ai vu et aussitôt, il y a un écouteur d'évènements digne de ce nom.
Non, j'avoue ne pas l'avoir fait, je regarde cela pour ce soir et je t'informe

**Comment by WREATCHED** [comment]
**En résumé** Ouah pleins de nouvelles versions
# Python < 3.8
zipp==3.7.0  ; python_version < '3.8' --> **3.11.0**
typing_extensions==4.1.1  ; python_version < '3.8' --> **4.4.0**
importlib_metadata==4.11.3  ; python_version < '3.8' --> **6.6.0**

# Python All
six==1.16.0  --> pas de changement
isodate==0.6.1 --> pas de changement
pyparsing==3.0.7 --> **3.0.9**
setuptools==65.6.3
rdflib==6.1.1 --> **6.2.0**

**Comment by alhyss** [comment]
Pour résumer, Plume n'est pas compatible avec RDFLib 6.2.0 à cause du problème décrit dans l'issue #119 et, à ce stade, je considère que c'est un dysfonctionnement de RDFLib, pas de Plume. C'est serait en outre très compliqué de corriger ça de notre côté, alors que c'est trivial du leur. Mais ils viennent tout juste de sortir une version, donc je doute qu'ils en publient une nouvelle dans les prochains jours... Le plus sage me semble être de revenir à RDFLib 6.1.1 pour Plume 0.7.0 bêta, et nous passerons ensuite directement à la première version qui corrige le problème. Est-ce que ça te va @WREATCHED ?

Il y a un autre changement introduit par RDFLib 6.2.0 dont j'ai retrouvé la trace dans mes tests, parce qu'il produit l'apparition d'avertissements qui n'étaient pas là auparavant. Mais tous les tests passent toujours au final et, cette fois, il s'agit une amélioration dont nous devrions profiter - cf. issue #120.

**Comment by WREATCHED** [comment]
Oui, je suis d'accord,

Je viens de poussé une version avec le paquet RDFLib r**dflib-6.1.1-py3-none-any.whl**
et modifié le **requirement.txt**

**Comment by alhyss** [comment]
Ok ! Je n'ai pas d'environnement de test avec Python < 3.8, mais pour le reste j'ai fait tourner mes tests en m'assurant d'avoir exactement les bibliothèques dans les versions de `requirements.txt`, et il n'y a pas d'autre problème.

La mise à jour descendante de RDFLib s'est bien exécutée, même si les utilisateurs n'en auront a priori pas besoin.

Bref, côté bibliothèques, tout m'a l'air en ordre pour publier la 0.7.0 bêta.
