### ISSUE TITLE
Import/export de modèles

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#109]
Fonctionnalité à ajouter, notamment pour faciliter la copie des modèles d'une base à une autre.

Principe : 
* Dans l'interface de gestion des modèles de Plume, l'utilisateur pourra non seulement supprimer un modèle sélectionné, mais aussi l'exporter. 
* Un bouton d'import lui permet également de réintégrer ses anciens exports.
* Les exports sont en JSON, dans le format utilisé par Plume pour ses modèles locaux. Celui-ci devra être complété pour intégrer la définition des catégories utilisées par le modèle (catégories locales, évidemment, mais communes également puisqu'elles ont pu être personnalisées) et la définition complète des onglets.
* L'utilisateur devrait pouvoir choisir si, lors de l'import, il souhaite ou non écraser les informations pré-existantes dans les tables des onglets et catégories. Les onglets et catégories manquants seront a priori ajoutés dans tous les cas, sauf à laisser à l'utilisateur la possibilité d'en supprimer du modèle par sélection manuelle.
* Les JSON, éventuellement ajustés en fonction de la configuration d'import, sont transcrits en requêtes SQL à exécuter sur la base (de préférence dans la même transaction).

**Comment by WREATCHED** [comment]
Hello @alhyss

**Comment by alhyss** [comment]
Pour l'export, est-ce que ça n'aurait pas été plus naturel d'utiliser l'arborescence *Liste des modèles* de l'onglet *Ressources* ? Au fond, elle contient exactement la même liste. Il pourrait y avoir un bouton *Exporter les modèles sélectionnés* dans le menu contextuel, et éventuellement un bouton *Exporter tous les modèles* pour tout exporter sans avoir à sélectionner ?

Je ne sais pas si l'import mérite un onglet non plus. Ça pourrait être une juste une action supplémentaire dans le menu ![Configuration](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/general/configuration.svg), qui ouvre une boîte de dialogue avec la case à cocher + la sélection du fichier source ? Accessoirement, procéder comme ça aurait aussi l'avantage de t'éviter d'avoir à te préoccuper de rafraîchir quoi que ce soit dans la boîte de dialogue *Gestion des modèles*.

**Comment by WREATCHED** [comment]
Ce n'est pas une question d'implémentation, amis d'ergonomie.
Le nombre d'information dans ressources est déjà assez riche et je ne trouve pas cela intuitif.
Alors qu'un onglet supplémentaire me parait plus clair

**Comment by WREATCHED** [comment]
**Après concertation**
**Pour l'import**
- Implémenter un nouvel item dans le menu de la barre de menu de plume.
   On aurait donc : 
   - Personnalisation de l'interface
   - Gestion des modèles
   - Import des modèles
      - Mettre à jour les tables des catégories et des onglets
      - Ne pas mettre à jour les tables des catégories et des onglets

**Pour l'export**
- Autoriser la multi sélection avec la touche Ctrl
- Implémenter le menu contextuel dans l'onglet "Ressources" du volet "Liste des modèles" avec l'item "Exporter le ou les modèle(s)"
   - Si multi sélection, envoyer la liste des id des modèles sélectionnés.
- Implémenter le menu contextuel dans l'onglet "Ressources" du volet "Liste des modèles" avec l'item "Exporter tous les modèles"

**Comment by WREATCHED** [comment]
**Problème détecté à l'import**
L'import des modèles pose des problèmes et plante Qgis (Plume) lorsque l'on a dans les champs jsonb, des valeurs décrites sous la forme de dictionnaire. 
psycopg2 ne parvient pas à les convertir.
voir sql.py 
- ligne 122 ``rv.append(i.as_string(context))``
- ligne 387 ``a = ext.adapt(self._wrapped)``

Quelques captures d'écran
![image](https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/98a2db8c-b2ec-462b-8c0d-efb1236ef032)
![image](https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/26fbc562-c495-4a18-9c6e-680db1ee1bd9)

**Comment by WREATCHED** [comment]
**Coté Qgis**
Tous les menus ont été implémentés
- Pour l'import de la barre de menu de plume.
- Pour l'export, dans le menu contextuel dans l'onglet "Ressources" du volet "Liste des modèles" avec l'item "Exporter le ou les modèle(s)"

![image](https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/a497eb29-34cb-450a-8735-abff9c38fddd)

**Coté bibliothèque**
Il ne reste que la partie @alhyss pour les champs jsonb 
- compute_params de template_categories
- md_conditions de template
- compute_params de catégories
