### ISSUE TITLE
Gestion des ToolTip dans le Dock de Asgard Menu

### ISSUE THREAD

**Issue by WREATCHED** [MTES-MCT/metadata-postgresql#113]
**Contexte** 
 - Plume qui sauvegarde les informations dans le champ commentaire de l'objet survolé, par exemple une table, fait apparaitre le Json-ld dans l'infobulle, ce qui se caractérise par une pollution visuelle et cela devient gênant au quotidien.
 - Aujourd'hui, Plume prend en compte la possibilité de changer les infobulles dans les explorateurs de Qgis (Browser1 et Browser2).
En fait, cette fonctionnalité est un vrai plus et se configure aisément.

**Constat**
Cette fonctionnalité ne prend pas en compte l'explorateur d'Asgard Menu et rend difficile son utilisation

**Action**
Implémenter Plume pour offrir la même fonctionnalité

**Visualisation du problème**
![image](https://user-images.githubusercontent.com/66324136/218035992-42570d15-8c25-41d0-912a-2c873d06dbe5.png)

**Comment by WREATCHED** [comment]
**Implémentation pour ce résultat**
![image](https://user-images.githubusercontent.com/66324136/220138340-ab1810b2-5987-4608-8a7a-ab68a690ae19.png)

**Comment by WREATCHED** [comment]
**La réponse en vidéo**
https://user-images.githubusercontent.com/66324136/220142004-a9265cb3-a400-4d81-830e-4117168d999f.mp4

**Comment by alhyss** [comment]
Probablement juste un contrôle d'existence qui manque, mais j'ai une erreur à l'activation de Plume avec la nouvelle version.

```
Impossible de charger l'extension 'plume' provoque une erreur lors de l'appel à sa méthode initGui() 

AttributeError: 'MainPlugin' object has no attribute 'navigateurasgardMenuDock' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS 3.22.8/apps/qgis-ltr/./python\qgis\utils.py", line 448, in startPlugin
    plugins[packageName].initGui()
  File "C:\Users/alhyss/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\plume\plume.py", line 78, in initGui
    self.initializingDisplayPlume()
  File "C:\Users/alhyss/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\plume\plume.py", line 131, in initializingDisplayPlume
    self._myExploBrowserAsgardMenu = MyExploBrowserAsgardMenu(self.navigateurasgardMenuDock.findChildren(QTreeView)[0], self.dicTooltipExiste, self.activeTooltip, self.activeTooltipColorText, self.activeTooltipColorBackground, self.langList, iconSourceTooltip,  self.activeTooltipLogo,  self.activeTooltipCadre,  self.activeTooltipColor, self.activeTooltipWithtitle)
AttributeError: 'MainPlugin' object has no attribute 'navigateurasgardMenuDock'
```

J'ai d'abord eu l'erreur alors que mon extension AsgardMenu était désactivée, puis alors qu'elle était activée mais sans l'affichage sous forme de panneau. En affichant le panneau, je n'ai plus d'erreur.

**Comment by WREATCHED** [comment]
Corrigé ce jour pour la 0.7.0 Bêta

**Comment by alhyss** [comment]
Pour autant que je puisse, plus de problème. Merci d'avoir fait si vite !
