### ISSUE TITLE
Trigger plume_stamp_data_edit sur toutes les tables installées

### ISSUE THREAD

**Issue by thiegaillard** [MTES-MCT/metadata-postgresql#114]
Bonjour,

y-a-t-il une fonction PostgreSQL permettant d'ajouter le trigger plume_stamp_data_edit sur toutes les tables installées avant l'installation de plume ?

Merci d'avance pour votre réponse.

**Comment by alhyss** [comment]
Bonsoir @thiegaillard 
Désolée pour le retour tardif. 

Non, il n'y a pas de fonction pour ça. Pour l'heure il faut exécuter la fonction `stamp_create_trigger` sur chacune des tables concernées, comme pour [activer le suivi au cas par cas](https://mtes-mct.github.io/metadata-postgresql/usage/gestion_plume_pg.html#suivi-au-cas-par-cas). Effectivement, c'est un manque !

En attendant, tu peux exécuter une boucle pour t'éviter d'avoir à traiter les tables une par une (exactement ce que fera la fonction que je vais écrire).

Par exemple, pour traiter toutes les tables du schéma `loop_test` :
```sql
DO
$$
DECLARE
	r record ;
BEGIN
	FOR r IN (SELECT oid FROM pg_class WHERE relnamespace = 'loop_test'::regnamespace)
	LOOP
		PERFORM z_plume.stamp_create_trigger(r.oid) ;
	END LOOP ;
END
$$
```
