### ISSUE TITLE
Déchargement du plugin

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#123]
Il serait bien d'implémenter la méthode `plume.plume.MainPlugin.unload`, qui définit les actions à exécuter lors du déchargement du plugin, pour qu'elle supprime au moins les éléments visibles sur lesquels l'utilisateur est susceptible de cliquer : bouton Plume dans la barre d'outils et dans le menu *Extensions*, panneau Plume... À voir s'il faudrait aussi stopper les actions de Plume sur les explorateurs et le panneau d'AsgardMenu, et peut-être d'autres choses que j'oublie.

https://github.com/MTES-MCT/metadata-postgresql/blob/6a9f8f42160b11ef0e4980f2ac23503a7fa9f6bc/plume/plume.py#L182

**Comment by WREATCHED** [comment]
Implémenté
````
  def unload(self):
      self.menu.deleteLater() 
      self.toolbar.deleteLater()
      pass  
````
