### ISSUE TITLE
Nettoyage des commandes d'import

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#126]
Côté @alhyss : 
* [x] Une commande d'import par package.

Côté @WREATCHED : 
* [x] Une commande d'import par package.
* [x] Utiliser de préférence des chemins absolus.
* [x] Nommer tous les objets importés.

**Comment by WREATCHED** [comment]
J'aimerai bien que l'on fasse une 0.8.0 pour tests des membres du GT avec toutes les révisions et donc modifications du code.
