### ISSUE TITLE
Masquage provisoire des options de gestion des modèles

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#127]
J'ai l'impression que le paramètre qui décide le masquage des options de gestion des modèles n'est pas systématiquement pris en compte.

Il l'est pour l'écran d'accueil : 
![masquage_gestion_modeles_ok](https://user-images.githubusercontent.com/55992003/234930712-3edbebdf-b721-4f9d-b1bd-35e2fd5d679d.png)

Il ne l'est semble-t-il plus dès qu'une fiche de métadonnées est affichée : 
![masquage_gestion_modeles_pas_ok](https://user-images.githubusercontent.com/55992003/234930740-912c9eed-4207-49ab-b246-018017a257f8.png)

Si je reviens sur l'écran d'accueil, le menu disparaît de nouveau.

Dans la fenêtre de configuration, ça a l'air plus compliqué que ça. Lorsque Plume est activé sur l'écran d'accueil, l'onglet *Modèles* n'est (comme il se doit) pas là. Si je charge une fiche, il apparaît. Si je reviens sur l'écran d'accueil, il reste, pour autant que je puisse voir.

![masquage_gestion_modeles_pas_ok_onglet](https://user-images.githubusercontent.com/55992003/234931051-7d2bd153-43b5-498b-b3d2-f0532f539366.png)

**Comment by WREATCHED** [comment]
Le problème vient du fait que je n'ai pas désactivé (c'est pas bien de ma part) la ligne 81 du code dans bibli_plume.py qui permet quelque soit le profil utilisé, de retourner False et donc de ne pas avoir accès à la gestion des modèles

**Comment by alhyss** [comment]
@WREATCHED J'allais clore l'issue, mais est-ce que ce serait envisageable, tant que les développements sont en cours, de gérer ça avec un paramètre de configuration qui vaudrait `False` par défaut chez tout le monde et que toi seul basculerait sur `True` dans ton QGIS3.ini ? Ça éviterait d'avoir à y penser à chaque fois que tu pousses des modifications sur le Git. 

Ce ne serait pas pour la v1.0, mais pour les prochaines versions jusqu'à ce que la gestion des modèles soit prête pour la diffusion.

**Comment by WREATCHED** [comment]
Complétement d'accord.
