### ISSUE TITLE
Donner accès aux modèles locaux si PlumePg ne fournit aucun modèle

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#131]
Actuellement, lorsque l'extension PostgreSQL PlumePg n'est pas installée sur la base contenant la table cible, l'utilisateur a tout de même accès aux modèles pré-configurés grâce à des copies locales. Par contre, lorsque PlumePg est installée mais qu'aucun modèle n'a été chargé/créé (`z_plume.meta_template` est vide), l'utilisateur n'a plus que *Aucun* (pas de modèle), dans sa liste de modèles disponibles.

Le formulaire sans modèle étant particulièrement lourd, notamment en mode édition, il paraît préférable de s'assurer que les utilisateurs ne se retrouvent jamais dans cette situation, et de donner accès aux modèles locaux lorsque PlumePg ne fournit pas de modèle.

**Comment by alhyss** [comment]
Je pense que c'est de ton côté qu'il faut gérer ça, @WREATCHED .

Ce ne sera a priori pas une très grosse modification, mais pas tout à fait trivial non plus.

Tu pourrais faire en sorte que la fonction `plume.bibli_plume.returnObjetTpl_label` utilise les modèles locaux lorsqu'elle n'en trouve pas sur le serveur en remplaçant : 
```python
    if option == "LOCAL" :
       mKeySql = queries.query_evaluate_local_templates(self.templates_collection, self.schema, self.table)
    else :   
       mKeySql = queries.query_list_templates(self.schema, self.table)
```

par quelque chose de ce genre : 
```python
   mKeySql = None
    if not option == "LOCAL" :   
       mKeySql = queries.query_list_templates(self.schema, self.table)
    if not mKeySql :  
       mKeySql = queries.query_evaluate_local_templates(self.templates_collection, self.schema, self.table)
```

Mais il faudra aussi : 
- mémoriser d'une manière ou d'une autre le fait que tu utilises finalement des modèles locaux, pour aller ensuite les chercher au bon endroit. 
- charger les modèles locaux dans `self.templates_collection` avant de lancer `queries.query_evaluate_local_templates()`, car l'attribut n'est (je crois) initialisé avec le constructeur de `plume.pg.template.LocalTemplatesCollection` que lorsque *PlumePg* n'est pas active sur la base.
   C'est ici : 
   https://github.com/MTES-MCT/metadata-postgresql/blob/f9e153e91fc75adb7b6b53c36eba64e0ecec61b4/plume/plume_ui.py#L1011

Je ne creuse pas plus, tu sauras mieux que moi comment intelligemment réorganiser ça !

*Référence doc technique : [Modèles de formulaire > Avec les modèles stockés en local](https://mtes-mct.github.io/metadata-postgresql/usage/modeles_de_formulaire.html#avec-les-modeles-stockes-en-local)*

**Comment by WREATCHED** [comment]
Réponse
instancier une nouvelle variable complémentaire à ````instalMetadata```` appelée ````ifNotEmptyTemplates ````
````
_schema, _table = "z_plume", "meta_template"
mKeySql = queries.query_list_templates(_schema, _table)
self.templatesEmptyOrPlain, zMessError_Code, zMessError_Erreur, zMessError_Diag = executeSql(self, self.mConnectEnCours, mKeySql, optionRetour = "fetchall")
self.ifNotEmptyTemplates = True if len(self.templatesEmptyOrPlain) > 0 else False
````
