### ISSUE TITLE
Comportement inadéquat au survol d'une couche dans le panneau explorateur de QGIS

### ISSUE THREAD

**Issue by StormKlaus** [MTES-MCT/metadata-postgresql#139]
Bonjour,

Suivant actuellement une formation sur PostgreSQL / PostGIS, j'ai été amené à faire une **vue** lors d'un exercice.
**Ma vue a été mal écrite** en première instance et elle entraine un comportement qui me semble non désiré.
La vue bien écrite ne génère évidemment pas ce comportement.

**Description du comportement :**
Lorsque que je survole la vue en question avec ma souris dans le panneau explorateur de QGIS, sans cliquer, une fenêtre s'ouvre et me demande le SCR. On peut par la suite définir et valider le SCR dans cette fenêtre mais rien se passe par la suite.
Le phénomène survient autant de fois que l'on survole cette vue mal écrite.

Voici le SQL (épuré) de ma vue mal écrite qui génère ce comportement :

```
CREATE VIEW travail.vue_zonage_pour_bug AS
SELECT
a.gid AS gid,
ST_POINT(
    (CASE WHEN b.gid IS NULL THEN ST_X(ST_CENTROID(a.geom)) ELSE b.x_etiq END),
    (CASE WHEN b.gid IS NULL THEN ST_Y(ST_CENTROID(a.geom)) ELSE b.y_etiq END)) AS geom
FROM  travail.zonage a
LEFT JOIN travail.zonage_etiq b ON a.gid = b.gid
;
```

Cordialement,

**Comment by alhyss** [comment]
@WREATCHED Je flèche sur la v1.0 pour la solution court terme - correction si possible, à défaut suppression temporaire des informations sur le référentiel (voire le type de géométrie) dans les infobulles re-générées par Plume. S'il y a besoin de procéder en deux temps, on créera une seconde issue pour le second temps.

Merci pour le retour, @StormKlaus ! Les vues (ou même table) avec des géométries sans référentiel ne sont pas un cas rare, il faut effectivement qu'on fasse en sorte que Plume ne complique pas les choses.

**Comment by WREATCHED** [comment]
@StormKlaus 
Peux-tu préciser la version de QGIS utilisée ?
Merci

**Comment by StormKlaus** [comment]
Yes
QGIS 3.22.6-Białowieża

**Comment by WREATCHED** [comment]
Effectivement si on modifie les options du SCR par tout sauf "Demander le SCR", ça passe
![image](https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/2dcd1991-668b-4c56-9e65-2e92578f027c)

**Comment by alhyss** [comment]
@WREATCHED Il faudra peut-être aussi vérifier ce qui se passe avec les utilitaires d'aide à la saisie des géométries du formulaire de Plume dans ce cas, que QGIS soit paramétré pour demander le référentiel ou non.

**Comment by WREATCHED** [comment]
**Analyse**

**Comment by WREATCHED** [comment]
**Retour @StormKlaus** 
Le 31/05/2023 à 11:00, SALE Aurélien - DDTM 40/MCPT/PG a écrit :
Bonjour à tous,

Le problème est en parti réglé.

Au survol : OK. Infobulle : OK ;
Au clic (juste le focus/sélection dans l'explorateur) -> même comportement -> boîte de dialogue de QGIS pour le SCR. On valide le 2154 et rien.

**Réponse @WREATCHED** 
Aurélien,
Je constate comme toi l'ouverture de la boite de dialogue de saisie des systèmes de projection. Et si je saisi le SRC, j'ai l'ouverture dans le CanVas et je n'ai pas de problème.
Survol et constitution de l'infobulle : OK
Simple clic , aucun événement n'y ouverture de boite  et pas de blocage et apparition de l'infobulle : OK
Double clic : Ouverture de la boite de dialogue des SRC et après choix, chargement de la couche et OK

Peux-tu m'expliquez ce qui ne va pas de ton coté ?

**Comment by WREATCHED** [comment]
Je viens de voir le comportement 
Au simple clic , il faut faire annuler pour que les métadonnées s'affiche dans l'IHM de Plume et que l'infobulle apparaisse.

**Comment by WREATCHED** [comment]
Je te retourne une nouvelle version, si tu peux tester avant

**Comment by WREATCHED** [comment]
**Corrige**

Je viens de terminer la correction pour le bug recensé ou plutôt le dysfonctionnement de Plume lorsque qu'une couche (SQL) n'est pas optimisée notamment pour son système de projection.
Désormais Plume au survol affiche la toolTip modifiée ou non et au simple clic, demande une fois la boite de dialogue pour en saisir un.
On peut ainsi gérer les MD même pour ce type de couche.
Je viens de passez presque une heure avec Aurélien que je remercie pour sa disponibilité , sa réactivité et son efficacité.
Il a eu sa part de contribution active pour nous dénicher des coquilles sous Plume.

**Technique**
Complément des évènements ````QtCore.QEvent```` de ma classe ````MyExploBrowser````
