### ISSUE TITLE
A-t-on besoin des millisecondes ?

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#14]
*À soumettre au sous-groupe Métadonnées.*

Pour l'heure, Plume tronque les heures à la seconde. Serait-il pertinent de prévoir la saisie des heures avec une précision à la milliseconde pour les métadonnées de type heure (`xsd:time`) et/ou date+heure (`xsd:dateTime`) ?

**Comment by thiegaillard** [comment]
Dans le cadre où des tables PostgreSQL seraient utilisées par un certains type d'applicatif, cela aurait un sens. Mais dans le cadre d'un entrepôt de données, ce que fait Plume est largement suffisant.
