### ISSUE TITLE
Checklist pour la diffusion d'une nouvelle version

### ISSUE THREAD

**Issue by WREATCHED** [MTES-MCT/metadata-postgresql#142]
![image](https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/36f3e84f-7f98-4e2b-b64f-cbdc7115a4cf) PLUME
# Checklist pour la diffusion d'une nouvelle version

## Sauvegarde
 - Sauvegarder le plugin (zip, 7z) via l'explorateur

## Générer un ZIP propre du plugin
 - Créer le zip d'installation avec zip_plume() qui se trouve sur le GitHub
 ### Procédure
 - Pour générer une archive utilisable par QGIS pour installer le plugin Plume, expurgée des fichiers de tests et autres éléments sans intérêt pour les utiliseurs, on exécutera :
```from admin.zip_plume import zip_plume``` et ```zip_plume()```
  Par défaut, le fichier ZIP est créé à la racine du dépôt, mais on pourra fournir en argument à admin.zip_plume.zip_plume le chemin absolu d’un autre répertoire cible. Dans tous les cas, l’archive sera nommée plume.zip.
 

### QGIS3.ini
 - Supprimer la section [PLUME] dans le fichier QGIS3.ini
### Bibliothèques
 - Désintaller rdflib via pip
   - Ouvrir une session shell dans l'environnement du Qgis et tapez : ```pip uninstall rdflib```

## Installation
 - Installer Plume à partir du gestionnaire d'extension sous Qgis
### Fermer et relancer Qgis
 - la boite de dialogue d'installation ou de mise à jour des bibliothèques doit apparaître
 - La barre d'outil de Plume doit s'afficher

### Ouvrir le panneau d'Asgard Menu
 - Naviguer dans le panneau d'Asgard Menu et constater l'affichage des infobulles
### Ouvrir si ce n'est pas le cas, le panneau de l'explorateur
 - Naviguer dans le le panneau de l'explorateur et constater l'affichage des infobulles

### Ouvrir le panneau d'Asgard Menu
 - Naviguer dans le panneau d'Asgard Menu et constater l'affichage des infobulles
### Ouvrir si ce n'est pas le cas, le panneau de l'explorateur
 - Naviguer dans le le panneau de l'explorateur et constater l'affichage des infobulles
### se connecter sur une base de données **sans** l'extension plume_pg
 - Vérifier que les trois modèles locaux soient disponibles
 - En mode edition, naviguer de l'un à l'autre et constater les changements dans l'interface
 - Saisir une information et sauvegarder
 - Ouvrir la boite de personnalisation de l'interface et changer quelques paramètres
 - Fermer et ouvrir Plume, puis constater les changements dans l'interface
### se connecter sur une base de données **avec** l'extension plume_pg
 - Vérifier que les trois modèles locaux soient disponibles ainsi que ceux importés dans PostgreSQL
 - En mode edition, naviguer de l'un à l'autre et constater les changements dans l'interface
 - Saisir une information et sauvegarder
 - Ouvrir la boite de personnalisation de l'interface et changer quelques paramètres
 - Fermer et ouvrir Plume, puis constater les changements dans l'interface
 - Changement de thésaurus dans les listes déroulantes
### Barre d'outils de Plume (clic sur les boutons et constat)
 - Edition
 - Copier / Coller / Vider
 - Sauvegarde
 - Traduction
 - Export / import

**Comment by alhyss** [comment]
@WREATCHED J'ai copié ton processus de test dans une nouvelle page [Test de l'interface utilisateur](https://mtes-mct.github.io/metadata-postgresql/mechanism/ui_test.html) de la documentation technique. 

Le fichier source, que tu peux modifier à volonté, est [`docs/mechanism/ui_test.md`](https://github.com/MTES-MCT/metadata-postgresql/blob/main/docs/mechanism/ui_test.md). La documentation HTML se met automatiquement à jour lorsque que tu pousses sur le Git des modifications des sources, dans un délai de quelques minutes (ou plus précisément dès que le point orange à côté de l'identifiant du commit se transforme en signe ✔️).
