### ISSUE TITLE
Retours à la ligne automatiques dans les QLabel

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#144]
Les retours à la ligne automatiques sur les `QLabel` semblent avoir disparu pour moi.

Je suis sous QGIS 3.22.8.

![no_wordwrap](https://github.com/MTES-MCT/metadata-postgresql/assets/55992003/46906e88-af84-4036-b3c3-36c776e19520)

**Comment by alhyss** [comment]
Ok, je compris d'où ça vient, et ce n'est pas un problème d'activation du retour à la ligne. Il est bien actif, mais il y avait dans ma fiche de test une valeur que QT n'arrive pas à découper. La largeur est calculée sur celle-là et, comme les paragraphes ne sont pas si long, c'est pour ça qu'au final il n'y a pas de retour à la ligne visible.

Fiche de métadonnées récupérée via l'import CSW INSPIRE : http://catalogue.geo-ide.developpement-durable.gouv.fr/catalogue/srv/fre/catalog.search#/metadata/fr-120066022-jdd-b68be6c4-ef98-40df-88b0-d2a0979c5ff4.

La valeur qui pose problème : https://ogc.geo-ide.developpement-durable.gouv.fr/csw/all-dataset?REQUEST=GetRecordById&SERVICE=CSW&VERSION=2.0.2&RESULTTYPE=results&elementSetName=full&TYPENAMES=gmd:MD_Metadata&OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd&ID=fr-120066022-jdd-b68be6c4-ef98-40df-88b0-d2a0979c5ff4

Vu qu'il y aura des URL de ce genre dans toutes les fiches de métadonnées de GéoIDE, ce serait bien de pouvoir paramétrer le retour à la ligne pour autoriser les coupures sur le caractère `&` (et potentiellement `=` aussi). Mais ce n'est pas dramatique si ce n'est pas possible.

**Comment by WREATCHED** [comment]
**réponse en vidéo**
https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/7137dc05-f2b5-45ce-bb3a-0fd784c10ffd

**Comment by WREATCHED** [comment]
Après réflexion et de nombreux tests, la gestion des retours à la ligne avec la méthode setMaximumWidth() n'est pas complétement satisfaisante lorsque l'on retrouve les QLabel avec des URL dans des onglets spécifiques (voir le modèle INSPIRE).

 - Il est convenu donc que les URL retournées par la clef 'value' ne retourne qu'une partie (excluant la fin de l'URL dès lors que l'on trouvera les caractères spéciaux &, = , etc) et faire suivre l'URL par .... (trois petits points).
   L'url via la balise <a> aura l'URL complète pour avoir le lien hypertexte.
 - L'URL complète sera écrite dans l'infobulle.
   Donc le WidgetKey retournera pour les infobulles : 
   la clef "help text" pour les QLabel (Etiquettes) et la clef "**value** help text" pour les QLabel contenant des URL.
 - Dans le cas où la clef "value help text" sera égale à "", on prendra la valeur de la clef "help text"

**Comment by WREATCHED** [comment]
ça ne coupe pas bien 
Voilà ce que j'ai 
![image](https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/adf160f3-acd9-421c-b8e4-490fb41c2746)

**Comment by WREATCHED** [comment]
Cool 👍  Testé ce jour.
Tout est OK pour moi, je tag "**résolu**"
![image](https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/8722ce19-a74c-4943-b150-5079c5acabcc)
