### ISSUE TITLE
Avertir l'utilisateur lorsque le serveur CSW renvoie une erreur

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#146]
Actuellement, la méthode `Ui_Dialog_ImportCSW.returnXml()` du module `plume.importcsw` n'avertit pas l'utilisateur lorsque le CSW a renvoyé une erreur. Dans ce cas, la méthode `contentAsString()` de l'objet [`QgsNetworkContentFetcher`](https://qgis.org/pyqgis/3.10/core/QgsNetworkContentFetcher.html) ne renvoie rien et, selon l'option d'import choisie par l'utilisateur, la fiche de métadonnées sera soit laissée intacte, soit entièrement vidée, sans que l'utilisateur ne sache pourquoi.

https://github.com/MTES-MCT/metadata-postgresql/blob/7f7818eb8c1b7884c8c495d6d49488c1c7eb7502/plume/importcsw.py#L365

Il n'y a aucune dysfonctionnement de Plume, mais l'utilisateur n'a aucune information pour l'aider à diagnostiquer le problème (si tant est qu'il remarque qu'il y en a un), qui peut aller du proxy mal configuré empêchant la connexion à internet à une coquille dans l'identifiant de la fiche de métadonnées.

La méthode `QgsNetworkContentFetcher.reply()` fournit un objet [`QNetworkReply`](https://doc.qt.io/qtforpython-5/PySide2/QtNetwork/QNetworkReply.html), sur lequel il est possible d'appliquer les méthodes `error()` et `errorString()` pour accéder aux informations sur les erreurs rencontrées. Il serait utile de les utiliser pour détecter les erreurs et afficher alors un message à l'utilisateur avec la description de l'erreur.

**Comment by WREATCHED** [comment]
**Analyse**
Dans le cas où la méthode contentAsString() de l'objet [QgsNetworkContentFetcher](https://qgis.org/pyqgis/3.10/core/QgsNetworkContentFetcher.html) renvoie rien,  [QgsNetworkContentFetcher.reply()| retourne **None**.
On ne peut donc pas retourner les méthodes error() et errorString()

On en parle ?

**Comment by WREATCHED** [comment]
Je reviens sur ma position, [QgsNetworkContentFetcher.reply()| ne retourne pas None et donc, on peut capturer les erreurs
Résultat ci-dessous
![image](https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/9a7aaea0-0918-4edf-b575-973bcdc4fcbc)

**Comment by alhyss** [comment]
Pour mémoire, la solution mise en oeuvre ne fonctionne que sur les erreurs HTTP (page introuvable, délai de réponse du serveur dépassé, etc.). Si les paramètres de la requête ne sont pas bons, notamment l'identifiant de la fiche de métadonnées, le CSW renvoie un XML certes sans métadonnées, mais qui contient tout de même un élément `csw:GetRecordByIdResponse`. Vérifier si la méthode `QgsNetworkContentFetcher.contentAsString` renvoie une chaîne de caractères vides n'est donc pas suffisant.

À noter que la [version 3 du protocole CSW](https://docs.ogc.org/is/12-176r7/12-176r7.html#103) prévoit de renvoyer une erreur HTTP 400 dans ce cas (Bad request), mais ce n'était pas le cas avec la version 2.0.2 prise en charge par Plume.

**Comment by WREATCHED** [comment]
**Correction**
