### ISSUE TITLE
Infobulles des couches sans géométrie dans l'explorateur

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#147]
Pour les tables sans géométrie, Plume affiche uniquement le message _"en tant que table sans géométrie"_ de QGIS, même si la table a des métadonnées. Contrairement à ce à quoi s'attendrait l'utilisateur, il n'y a pas le message habituel pour prévenir de la présence de métadonnées, et le libellé qui aurait été extrait des métadonnées si la table avait eu une géométrie n'apparaît pas.

Est-il possible de reproduire dans ce cas le comportement normal des tables avec géométrie ?

**Comment by WREATCHED** [comment]
**Analyse**

**Comment by WREATCHED** [comment]
**Réponse**
![image](https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/0f4b4c0b-e6a3-4b34-98a2-8cd81ad88076)

Modification dans la classe MyExploBrowser

               if index != -1 and self.proxy_model != None :
                  self.itemLayer = self.model.dataItem(self.proxy_model.mapToSource(index))
                   
                  # Alimentation du dictionnaire des tooltip d'ORIGINE existantes"
                  if index in self._dicTooltipExiste :
                     itemLayerTooltip = self._dicTooltipExiste[index]
                  else :
                     if self.itemLayer !=  None and hasattr(self.itemLayer, 'comments') :
                        itemLayerTooltip = self.itemLayer.comments()
                     else :   
                        itemLayerTooltip = self.proxy_model.data(index, Qt.ToolTipRole)

**Comment by WREATCHED** [comment]
**Solution**
```
                  # Alimentation du dictionnaire des tooltip d'ORIGINE existantes"
                  if index in self._dicTooltipExiste :
                     itemLayerTooltip = self._dicTooltipExiste[index]
                  else :
                     if self.itemLayer !=  None and hasattr(self.itemLayer, 'comments') :
                        vComment = self.itemLayer.comments()
                        vToolTip = self.itemLayer.toolTip()
                        if vComment and vToolTip:
                            if vComment in vToolTip:
                                tooltip = vToolTip
                            else:
                                tooltip = f'{vComment}\n\n{vToolTip}'
                        else:
                            tooltip = vToolTip or vComment
                         
                        itemLayerTooltip = tooltip
                     else :   
                        itemLayerTooltip = self.proxy_model.data(index, Qt.ToolTipRole)
```
![image](https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/c583f07c-0d47-48da-a7e2-b6306e06e9d3)
