### ISSUE TITLE
Option pour intégration des commentaires de table

### ISSUE THREAD

**Issue by StormKlaus** [MTES-MCT/metadata-postgresql#151]
Bonjour, 

J'ai deux petites questions en rapport avec la reprise de notre patrimoine de métadonnées PostgreSQL formalisé avant le déploiement de PLUME :

- y'a t'il moyen d'importer le descriptif que l'on a déjà formalisé dans le "COMMENT ON TABLE" dans la champ Description de PLUME ?
-> une requête ? en attendant une future option ?

- y'a t'il moyen d'utiliser/importer le libellé formalisé dans le "COMMENT ON TABLE" pour Asgard Menu, dans le champ libellé de PLUME ? et vice-versa ?
-> exemple de libellé pour Asgard Menu : [IGN BDT - Commune]

Merci pour vos futures lumières.

Bonne journée

**Comment by alhyss** [comment]
Bonjour @StormKlaus 

C'est déjà possible - même si l'absence de documentation utilisateur rend difficile de le deviner à ce stade 😢

Pour importer le descriptif complet ou une partie dans le champ description `dct:description` ou le champ libellé `dct:title` de Plume, il faut utiliser un modèle qui active la fonctionnalité de calcul sur ces champs et définit une expression régulière adaptée. La [documentation technique](https://mtes-mct.github.io/metadata-postgresql/usage/metadonnees_calculees.html#principe) explique sommairement comment faire.

Comme pour toutes les fonctionnalités de calcul, tu as le choix entre deux comportements : 
- un mode manuel (`manual`). En mode édition, l'icône ![compute_button](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/buttons/compute_button.svg) apparaît dans la fiche de métadonnées et il faut cliquer dessus pour importer les éléments issus du descriptif.
- trois modes automatiques (`auto`, `empty`, `new`). En mode lecture comme en mode édition, les éléments sont automatiquement importés lors du chargement de la fiche de métadonnées, écrasant donc les métadonnées préalablement saisies. Évidemment, rien n'est enregistré tant que l'utilisateur n'a pas cliqué sur le bouton d'enregistrement ![save](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/general/save.svg), ce qui n'est possible qu'en mode édition. La documentation technique décrit précisément chacun des trois modes, l'idée générale est que `auto` s'active tout le temps, `empty` uniquement si le champ ne contenait aucune valeur, `new` uniquement à l'initialisation d'une nouvelle fiche de métadonnées.

Les modes doivent être spécifiés dans le champ `compute` du modèle, et les paramètres (notamment l'expression régulière à utiliser) dans le champ `compute_params`, sous la forme d'un dictionnaire JSON. Il est possible d'avoir à la fois le mode manuel et l'un des modes automatiques. 

Imaginons que tes descriptifs soient de la forme `[%libellé%] %description%` et que tu souhaites activer automatiquement cette fonctionnalité pour tous les modèles quand les champs description et libellés sont vides, tout en permettant une activation manuelle dans les autres cas.

Tu peux configurer les catégories de métadonnées `dct:title` et `dct:description` de cette façon :
```sql
UPDATE z_plume.meta_categorie
    SET compute = ARRAY['empty', 'manual'],
        compute_params = '{"pattern": "^[[]([^]]+)[]]"}'::jsonb
    WHERE path = 'dct:title' ;

UPDATE z_plume.meta_categorie
    SET compute = ARRAY['empty', 'manual'],
        compute_params = '{"pattern": "^(?:[[][^]]+[]])?\\n*\\s*(.+)$"}'::jsonb
    WHERE path = 'dct:description' ;
```

Pour activer la fonctionnalité sur un modèle particulier, il faut faire la même chose dans `z_plume.meta_template_categories` sur l'enregistrement qui associe la métadonnée au modèle en question.

Pour la boucle retour - copier la description et/ou le libellé des métadonnées dans le descriptif PostgreSQL - il faut aller dans les options de Plume : ![configuration](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/general/configuration.svg) *Personnalisation de l'interface*, onglet *Avancé*. Ce sont les deux cases à cocher du bas.

![copie_dans_descriptif](https://github.com/MTES-MCT/metadata-postgresql/assets/55992003/e176a275-5bcc-4196-aa81-9a66cc985df2)

Pour l'heure, il n'y a pas la possibilité de définir un formatage particulier pour le titre ou la description, et ils écrasent le descriptif PostgreSQL existant. Le titre est placé en premier, la description ensuite. Si les deux sont présents, ils sont séparés par un retour à la ligne. Cette fonctionnalité peut tout à fait être améliorée. Nous n'étions pas allés très loin, ne sachant pas si elle serait utilisée.
