### ISSUE TITLE
Suppression des géométries "oubliées"

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#154]
Lorsque l'utilisateur active la visualisation de métadonnées géométriques ![show](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/buttons/geo/show.svg), puis ferme le panneau de Plume sans avoir désactivé la visualisation ni changé de fiche de métadonnées, les tracés des géométries restent dans le canevas et l'utilisateur n'a aucune solution pour les faire disparaître hormis relancer QGIS.

L'idéal serait que la fermeture du panneau efface automatiquement les tracés, comme c'est déjà le cas lorsque la fiche de métadonnées est rechargée ou que l'utilisateur change de fiche de métadonnées.

**Comment by WREATCHED** [comment]
**Solution**
Implémentée
https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/bc9bf42a-5418-4c98-9f99-821f1cb0e106
