### ISSUE TITLE
Quels modèles de formulaire pré-configurés ?

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#16]
*À soumettre au sous-groupe Métadonnées.*

Considérant la très longue [liste de catégories de métadonnées communes](https://mtes-mct.github.io/metadata-postgresql/usage/metadonnees_communes.html), filtrer celles qui méritent d'être affichées paraît indispensable. La création de modèles étant elle-même une opération fastidieuse, il paraît judicieux que l'extension PostgreSQL *PlumePg* propose quelques modèles pré-configurés adaptés à des usages simples (et que les administrateurs pourront retoucher à leur convenance).

Reste à déterminer : 
1. Quels seraient ces modèles.
2. Quelles catégories de métadonnées ils feraient apparaître.
3. S'il est pertinent de les appliquer automatiquement dans certaines conditions.

Dans la version actuelle, trois ébauches de modèles pré-configurés sont disponibles et peuvent servir de base : 
- Modèle *Basique*, avec très peu de catégories affichées, qui pourrait être pertinent pour des utilisateurs peu familiers de la géomatique et des données.
- Modèle *Classique*, présentant davantage d'informations et qui s'applique automatiquement pour toutes les tables et vues des schémas du bloc *Consultation* (nom du schéma commençant par `c_`).
- Modèles *Donnée externe*, avec des catégories adaptées aux données produites par des tiers et qui s'applique automatiquement pour les tables et vues des blocs *Référentiels* (schémas préfixés par `r_`) et *Données externes* (schémas préfixés par `e_`) ou pour lesquelles la case "Donnée externe" / `plume:isExternal` a été cochée dans les métadonnées.

Cf. page [Modèles de formulaire](https://mtes-mct.github.io/metadata-postgresql/usage/modeles_de_formulaire.html) de la documentation technique (à défaut d'avoir encore une documentation utilisateur) pour plus de détails sur le fonctionnement des modèles et page [Métadonnées communes](https://mtes-mct.github.io/metadata-postgresql/usage/metadonnees_communes.html) pour la liste des catégories de métadonnées pouvant être ajoutées aux modèles pré-configurés.

**Comment by alhyss** [comment]
*Le sous-groupe Métadonnées du 13 juin 2022 acte :*
- *D'ajouter un modèle "INSPIRE" (nom non nécessairement définitif) basé sur les fiches de métadonnées de Géo-IDE Catalogue. Dans la mesure du possible : mêmes catégories, mêmes libellés, même onglets. Ce modèle a vocation à faciliter l'appropriation progressive de Plume par les administrateurs de données habitués aux catalogues INSPIRE. Il facilitera aussi le contrôle des métadonnées générées à partir de XML INSPIRE (import depuis un service CSW ou, à l'avenir, un fichier).*
- *Que le modèle "Basique" sera appliqué automatiquement aux tables du bloc `c_` (consultation), au lieu du modèle "Classique".*
- *D'ajouter les conditions d'accès au modèle "Basique".*
- *D'ajouter les conditions de réutilisation au modèle "Classique".*

*Il reste possible de proposer des évolutions supplémentaires via la présente issue jusqu'au 30 juin 2022.*

**Comment by DDT-16** [comment]
Pour la DDT16, on a repensé aux rubriques des modèles et on propose :

pour le modèle Basique,   
 ajouter 'Condition ou Restriction d'accès' (voir rubrique GI catalogue/MD principale, case à cocher) 
ajouter 'Statut de la données' (archivée, obsolètes, vivantes, à jour) comme dans GI catalogue/MD complémentaires/maintenance

Pour le modèle Classique :
ajouter en plus 'Condition ou restriction d'usage' (voir rubrique GI catalogue/MD principale)

**Comment by alhyss** [comment]
Implémenté : 
- ajout d'un modèle *INSPIRE* pour les métadonnées INSPIRE/ISO 19139 ;
- application automatique du modèle *Basique* au lieu de *Classique* aux tables des schémas préfixés de `'c_'` ;
- ajout des conditions d'accès au modèle *Basique* (`dct:accessRights`) ;
- ajout des conditions/limitation d'usage au modèle *Classique* (`dcat:distribution / dct:rights`) ;
- ajout de l'état du jeu de données (`adms:status`) à tous les modèles.

Le modèle INSPIRE comprend bien des onglets, par contre ses libellés restent standard pour l'heure. Quant à la répartition entre les onglets, elle vise plus à faciliter la saisie qu'à rappeler les usages d'autres catalogues. Cet aspect pourra être reconsidéré selon les retours des utilisateurs. Il n'est dans tous les cas pas possible d'avoir une correspondance exacte entre les catégories ISO et GeoDCAT-AP.
