### ISSUE TITLE
Plantage de Plume en activant la propriété `sql_filter`

### ISSUE THREAD

**Issue by WREATCHED** [MTES-MCT/metadata-postgresql#163]
**Contexte**
En utilisant une condition sur la propriété `sql_filter ` de la table z_plume.meta_template et que l'on ne saisit pas de nombre dans `priority  `, Plume se plante.

**Erreur** A confirmer
```
File "C:\Users/didier.leclerc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\plume\pg\template.py", line 232, in search_template 
    if r and (priority is None or priority TypeError: '
During handling of the above exception, another exception occurred:
```

**Comment by alhyss** [comment]
L'erreur se produit quand : 
- `priority`  vaut `None` pour le premier modèle dont la condition `sql_filter` ou `md_condition` est remplie.
- Ce n'est pas le dernier modèle de la liste.
- Le modèle suivant (ou l'un des modèles suivants tel que `p` n'est pas réaffecté entre temps) a une valeur dans `priority`.

Lorsque la boucle passe sur le modèle en question, la commande `p = priority` (ligne 239 ou 265) fait que la variable `p` est mise à `None`. Lors de l'itération suivante, `if r and (priority is None or priority <= p)` (ligne 232) échoue, puisqu'il n'est pas possible de comparer un entier avec `None`.

C'est trivial à corriger, j'essaie de te faire ça d'ici demain.

**Comment by WREATCHED** [comment]
**Testé, tout est OK**
