### ISSUE TITLE
Démultiplication du panneau Plume - comportement voulu ?

### ISSUE THREAD

**Issue by StormKlaus** [MTES-MCT/metadata-postgresql#171]
Bonjour,

Pour information,

J'ai constaté que si l'on cliquait plusieurs fois sur l’icône Plume dans QGIS,
celui-ci ouvre autant de panneau Plume que de fois que l'on a cliqué sur l’icône.

Est-ce le comportement voulu ?
J'ai pas de préférence quant au comportement escompté.

Et en première instance, j'ai l'impression que la cohabitation des différents panneaux se passe bien...

Cordialement,

**Comment by WREATCHED** [comment]
**Corrigé**
