### ISSUE TITLE
Réduire la taille de l'archive contenant le plugin QGIS

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#175]
Modification de la fonction `admin.zip_plume.zip_plume` pour qu'elle compresse l'archive générée.

https://github.com/MTES-MCT/metadata-postgresql/blob/91a1d871b53bd00365d2eb8ab54c2837957487cb/admin/zip_plume.py#L25

**Comment by alhyss** [comment]
@WREATCHED J'ai fait la petite modification nécessaire. On passe d'un ZIP de 15 822 Ko pour la v1.1.0 à 2 981 Ko pour la version en cours de développement, ce n'est effectivement pas négligeable.

J'ai vérifié que QGIS arrivait à installer le plugin à partir de l'archive compressée, mais pas dans le cas où il y a besoin d'installer les bibliothèques. Il n'y a pas de raison que ça se passe mal, mais est-ce que tu pourras tout de même faire ce test-là avant de marquer l'issue comme résolue ?

La [commande pour générer le ZIP](https://mtes-mct.github.io/metadata-postgresql/mechanism/memo.html#generer-un-zip-propre-du-plugin) est toujours la même : 
```python
from admin.zip_plume import zip_plume
zip_plume()
```

**Comment by WREATCHED** [comment]
Test
- Taille du fichier 
   - Avant 15,6 Mo (16 441 344 octets)
   - Après 2,91 Mo (3 059 712 octets)
- Installation des bibliothèques OK
![image](https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/2cbd2299-6634-4ae5-9f51-a1f03c397118)
