### ISSUE TITLE
Import/export de modèles (pb avec les champs jsonb)

### ISSUE THREAD

**Issue by WREATCHED** [MTES-MCT/metadata-postgresql#178]
Fonctionnalité à ajouter, notamment pour faciliter la copie des modèles d'une base à une autre.

Contexte :
La fonctionnalité a été implémenté dans la version 1.1.1.

Constat : 
Il demeure un problème lors de l'import. En effet, l'import des modèles pose des problèmes et plante Qgis (Plume) lorsque l'on a dans les champs jsonb, des valeurs décrites sous la forme de dictionnaire.
psycopg2 ne parvient pas à les convertir.
voir sql.py

ligne 122 rv.append(i.as_string(context))
ligne 387 a = ext.adapt(self._wrapped)

Voir issue [#109 ](https://github.com/MTES-MCT/metadata-postgresql/issues/109#issuecomment-1809782126)

**Comment by alhyss** [comment]
@WREATCHED Je te laisse contrôler via l'interface, mais c'est corrigé. Les dictionnaires sont maintenant encodés en JSON préalablement à la génération de la requête.

Tu as vraisemblablement eu des erreurs similaires quand tu travaillais sur les requêtes de modification des modèles, mais j'imagine que tu as retiré des `json.loads` ou ajouté des `json.dumps` là où il fallait pour que ça fonctionne sans réaliser que le problème était de mon côté.
