### ISSUE TITLE
Gestion des modèles - Retours sous groupe métadonnées

### ISSUE THREAD

**Issue by WREATCHED** [MTES-MCT/metadata-postgresql#179]
## DIR SO - Pascal ASTRUC
- OK Version fonctionnelle et diffusable au grand public

## DDT 16 - Sylvie Girard
- OK mais pas testée toutes les fonctionnalités

### Fenêtre "Gestion des modèles" :
- [x] PB -> pas de possibilité de redimensionner la fenêtre ...
  - **Réponse** : Non, la fenêtre est bien redimensionnable
### Onglet "Constitution des modèles" :
- [x] PB -> créer un modèle à partir de la fenêtre de gestion des modèles -> ergonomie pouvant être amélioré  -> création nouveau modèle pas intuitif (clic droit et "Ajouter un modèle")
  - Solution ? ->  Ajout d'un bouton "+" pour créer un nouvel modèle/onglet + visualisation de la nouvelle ligne même si pas "Enregistrer"
  - **Réponse** : Non, c'est un choix fonctionnel *ou en attente de l'accord de LL (ajout d'un bouton à coté ou en dessous du libellé "Liste des modèles")*
    Vu avec LL => Envisager de créer une barre d'outils contextuelle 
  - [x]  **Réponse** : Insérer le texte "Nouveau modèle" lors du clique sur "Ajouter un modèle" dans le menu contextuel
- [x] PB -> Si premier modèle créé rendu "Actif", les autres modèles déployés par défaut disparaissent (Basique, INSPIRE, ...)
  - Solution ? -> garder et ou pouvoir gérer/modifier les modèles déployés par défaut, / avoir une option pour lancer la requête d'import des modèles pré-configurés depuis l'interface ? (SELECT * FROM z_plume.meta_import_sample_template())
  - **Réponse** : Oui, c'est un choix fonctionnel. Par contre cette fonction existe dans l'issue https://github.com/MTES-MCT/metadata-postgresql/issues/111
  - **Autre possibilité** : *Insérer un item "Import des modèles par défaut (Basique, Classique, Inspire, Données Externes)"*
    Voir https://mtes-mct.github.io/metadata-postgresql/usage/modeles_de_formulaire.html#chargement-des-modeles-pre-configures
![image](https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/ddb12b36-2bea-4939-93ec-16830de693ed)

Implémenté
![image](https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/37ac6e8b-0e36-40dd-beb4-3fb4bd4d5aad)

- [x] PB -> Obligation de fermer et ré-ouvrir Plume pour pouvoir ré-initialiser la liste des modèles et pouvoir utiliser le nouveau modèle
  - **Réponse** : Oui, c'est un choix fonctionnel
- [x] #183
  - **Réponse** : Oui, déjà évoqué en réunion, il faudrait l'implémenter dans une prochaine version
- [x] #182
  - **Réponse** : ??
- [x] -> Retranscription des MD utilisées -> interchanger les termes techniques et sa retranscription littéraire. ex : dct:provenance(Généalogie) -> Généalogie(dct:provenance)
  - **Réponse** : Non, pas implémenté
  - **Réponse** : *Dans l'interface de personnalisation, proposer deux boutons d'options pour interchanger le libellé et l'identifiant de la catégorie*
- [x] + avoir un classement des items par ordre alphabétique
  - **Réponse** : Non, pas implémenté
### Onglet "Ressources" :
   **Section "Liste des modèles" :**
- [x] PB -> lors de la saisie des commentaires du modèle, pas de possibilité d'avoir un visuel sur l'ensemble de la saisie
- [x] + avoir un champ de saisi redimensionnable
  - **Réponse pour les deux** : *Transformer le champ "Commentaire" et "Filtre SQL" d'un QLineEdit en QtextEdit sur deux lignes avec le scrolling automatique*

**(DL / AS) Réunion lundi 27/11/2023 14h00-15h00 pour analyse de chaque point**

**Comment by WREATCHED** [comment]
**Barre d'outils contextuelle dans la gestion des modèles**

![image](https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/858e339e-ddfd-45d5-a63e-d55336120f86)

https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/6e93e79d-cb50-4692-bf8e-34ac3881e21c

**Comment by StormKlaus** [comment]
Merci pour ces développements.
Cela me semble très bien, et cela sera assurément plus intuitif pour tous les nouveaux utilisateurs et facilitera la prise en main du plugin.
