### ISSUE TITLE
[Problème d'affichage sur plusieurs lignes]

### ISSUE THREAD

**Issue by WREATCHED** [MTES-MCT/metadata-postgresql#196]
**DDTM 40 - Aurélien SALE**
Retour sur utilisation par courriel du 22/02/2024

- [x] Je crois que j'ai découvert un petit bug.
   Quand je défini les valeurs par défaut de "Texte sur plusieurs lignes" et "Nombre de lignes" dans une catégorie de MD, voir capture d'écran, celles-ci ne se répercutent pas dans mon modèle ADL.
   Je suis obligé de forcer ces valeurs (les indiquer à nouveau) dans les paramètres des catégories de mon modèle ADL pour avoir, dans cet exemple, un champ texte sur plusieurs lignes en mode édition. Sinon j'ai juste un champ de saisi de type texte sur une seule ligne.
  Reproduis-tu le problème ?
  Peut-être que d'autres paramètres par défaut ne se répercutent pas bien, j'ai pas poussé l'analyse.

  **Réponse**
  Non, je ne reproduis pas le phénomène.
  Attention de bien une valeur par exemple "Texte non traduisible" pour que les deux informations soient prises en compte
  C'est indiqué dans l'aide
  
![image](https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/88ca80a8-6265-4322-8477-322f01987cca)

@StormKlaus, As-tu testé si c'est bien comme cela que ça fonctionne chez toi ?

**Comment by StormKlaus** [comment]
**Dans mon modèle ADL**, j'avais une coche de décochée au lieu qu'elle soit grisée (valeur pas défaut), du coup les paramètres de mon modèle ADL prenaient le dessus. (Paramètres avec des valeurs vides car je voulais les valeurs par défaut...)
-> Ce n'est donc pas un bug mais un mauvais paramétrage de ma part.
Encore merci
