### ISSUE TITLE
[Système de projection dans la définition des géométries]

### ISSUE THREAD

**Issue by WREATCHED** [MTES-MCT/metadata-postgresql#197]
**DDTM 40 - Aurélien SALE**
Retour sur utilisation par courriel du 22/02/2024

- [x] Autre chose, il me semble pas avoir vu de MD indiquant clairement le système de projection....
Je vois bien le code EPSG 2154 dans la retranscription textuelle WKT de mon rectangle d'emprise mais c'est tout... j'ai loupé quelque chose ?
Réponse
La première partie de la géométrie en format WKT (Well-Known Text) d'un polygone précise le système de coordonnées spatiales spécifique, identifié par l'URI http://www.opengis.net/def/crs/EPSG/0/2154.

Aurélien, si tu parles de la projection du champ géométrique, tu as la MD **dct.conformsTo** qui devrait répondre à ta question.
![image](https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/c14d9e8d-9fa0-4068-ad8e-7703e91c38a2)

@alhyss - Suite à ta demande, tu peux compléter.

**Comment by StormKlaus** [comment]
Ok c'est exactement ce que je cherchais. J'ai donc bien loupé quelque chose ! **Merci**
