### ISSUE TITLE
Boutons de calcul et calcul automatique

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#23]
Nouvelle fonctionnalité qui est maintenant implémentée côté dictionnaire de widgets : le calcul de métadonnées par une requête sur le serveur PostgreSQL.

Pré-requis : issue #22.

Dès lors qu'une méthode de calcul a été prévue dans Plume pour une catégorie donnée, le schéma des métadonnées communes et/ou le modèle de formulaire peuvent demander à ce que cette fonctionnalité soit mise en oeuvre, avec deux formes possibles : 
- exécution automatique à la génération du formulaire (option `'auto'`) ;
- exécution à la demande, quand l'utilisateur clique sur un nouveau bouton du formulaire dit *bouton de calcul* (option `'manual'`).

Cf. [Création des widgets](https://github.com/MTES-MCT/metadata-postgresql/blob/main/docs/source/usage/creation_widgets.md#widget-annexe--bouton-de-calcul) pour les modalités de création du bouton de calcul.
Cf. [Métadonnées calculées](https://github.com/MTES-MCT/metadata-postgresql/blob/main/docs/source/usage/metadonnees_calculees.md) pour toutes les explications sur les calculs eux-mêmes et l'implémentation du calcul automatique.

À noter que la seule catégorie pour laquelle j'ai défini une méthode de calcul côté serveur est `dct:conformsTo` (import de tous les référentiels de coordonnées déclarés pour les géométries de la table). L'idée sera d'en ajouter selon les besoins exprimés par le sous-groupe Métadonnées - cf. issue #21. J'ai fait en sorte que ce soit aussi simple que possible de mon côté. La mécanique est complètement générique, il faut juste que je référence la catégorie concernée, la fonction qui génère la requête, une éventuelle fonction de retraitement a posteriori s'il y a besoin de transformer un peu le résultat renvoyé par PostgreSQL, et quelques paramètres (extensions PostgreSQL requises, etc.). Côté gestion des widgets, les futurs ajouts devraient être complètement transparents.

**Comment by alhyss** [comment]
@WREATCHED Pour info, au cas où tu aurais commencé à travailler là-dessus, j'ai a priori fini d'implémenter ce qu'il y avait à faire pour l'issue #42 et ça ne change rien du tout de ton côté.

La seule chose que j'ai modifiée qui te concerne (sans lien avec l'issue #42), c'est pour le texte à afficher dans les infobulles, qui n'est plus le même pour tous les boutons de calcul. Cf. [documentation technique](https://mtes-mct.github.io/metadata-postgresql/usage/creation_widgets.html#id31).

**Comment by WREATCHED** [comment]
thanks 😃

**Comment by alhyss** [comment]
@WREATCHED Comme prévu, j'ai ajusté la méthode pour ne plus avoir de problème de dictionnaire qui change de taille pendant que Plume boucle dessus. C'est expliqué dans [Implémentation du calcul automatique](https://mtes-mct.github.io/metadata-postgresql/usage/metadonnees_calculees.html#implementation-du-calcul-automatique), mais pour faire simple, il y a deux choses à changer de ton côté.

- [ ] Supprimer ce que tu avais ajouté dans `plume.bibli_gene_objets.generationObjets` pour le calcul automatique, à savoir (vers la ligne 88) : 

```python
    # ** BEFORE SAISIE ** Mode automatique calcul des Métadonnées
    # Lorsque la clé correspond à un widget de saisie, le calcul doit avoir lieu avant la saisie de la valeur dans le widget
    if _valueObjet['auto compute'] :
       #
       action_mObjetQToolButton_ComputeButton(self, _keyObjet, _valueObjet, "BEFORE")
```

- [ ] Dans `plume.plume_ui.Ui_Dialog_plume.generationALaVolee`, ajouter une boucle de calcul automatique juste avant la boucle qui génère les widgets. C'est aux alentours de la ligne 483 dans ma version.

```python
        for key, value in _dict.items_to_compute():
            action_mObjetQToolButton_ComputeButton(self, key, value, 'BEFORE')
        for key, value in _dict.items() :
            ...
```

Il est normal que tu ne fasses plus de contrôle sur `'auto compute'`, c'est intégré dans mon générateur.

Sinon ne t'étonne pas de tous les commit que j'ai faits aujourd'hui. La grande majorité n'avait rien à voir avec ça : il s'agissait de faire en sorte que les calculs automatiques ait également lieu en mode lecture. On perdait beaucoup de l'intérêt d'avoir - par exemple - une date de dernière modification mise à jour automatiquement si Plume continuait à afficher la vieille valeur tant que personne n'ouvrait la fiche en mode édition...

**Comment by WREATCHED** [comment]
C'est Ok pour moi, je clos

**Comment by WREATCHED** [comment]
J'ai réouvert mais mis en résolu avant diffusion
