### ISSUE TITLE
Espace de nommage digne de ce nom pour les IRI de Plume

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#28]
Le schéma des catégories communes ([`shape.ttl`](/plume/rdf/data/shape.ttl)) introduit des IRI spécifiques à Plume dans deux cas : 
- Pour ajouter des classes et propriétés à celles prévues par GeoDCAT-AP. Par exemple la classe `snum:LinkedRecord` qui permet de lier la fiche de métadonnées locale à une fiche de catalogue distant, ou la propriété `snum:isExternal` de la classe `dcat:Dataset` qui indique sans équivoque si le jeu de données a été produit par un tiers.
- Pour toutes les options de configuration des propriétés qui n'existent pas nativement en SHACL (`snum:longText`, `snum:ontology`, `snum:placeholder`, etc.).

Pour l'heure, ces IRI utilisent comme espace de nommage `http://snum.scenari-community.org/Metadata/Vocabulaire/#`, ce qui n'est pas un espace de nommage pérenne. Nos ministères ne sont même pas propriétaires du domaine. Il serait judicieux de le remplacer.

**Mais quel espace de nommage, dans ce cas ?**

Cette opération doit être réalisée au plus tôt et impérativement avant toute diffusion à grande échelle, car ces IRI apparaîtront dans les fiches de métadonnées encodées dans les commentaires de objets PostgreSQL. Changer leur espace de nommage a posteriori nécessiterait que tous les administrateurs de serveurs PostgreSQL qui utilisent Plume exécutent un script SQL correctif mettant à jour les fiches tout en s'assurant en parallèle que la totalité de leurs utilisateurs utilisent bien la dernière version de Plume. Autrement dit, c'est délicat et mieux vaudrait éviter une telle situation.

Par la même occasion, il pourrait être envisagé de remplacer le préfixe associé (aujourd'hui `snum`) par `plume` ou `plm`. Ceci affectera les modèles gérés par *PlumePg* et, même s'il serait relativement simple de gérer une substitution a posteriori, mieux vaudrait qu'elle soit réalisée avant la diffusion de Plume.

**Comment by alhyss** [comment]
Nous avons l'accord principe d'Ecolab pour utiliser le domaine du guichet d'accès aux données du pôle ministériel.

Espace de nommage pressenti : `http://registre.data.developpement-durable.gouv.fr/plume/`.

Comme - avec un tel nom - il s'agira clairement de l'espace de nommage de Plume, `plume` me semble approprié comme préfixe.

À très court terme (diffusion en bêta au GT PostGIS), les URI ne seront probablement pas activables. À moyen terme, elles pourraient renvoyer vers une page de GéoInformations. À plus long terme, en particulier si d'autres besoins du même ordre émergent pour d'autres outils, une petite application pourrait être développée pour permettre à la fois une interrogation machine et l'accès à des informations lisibles par un être humain.

@GilGuillouet va faire le ticket au PSIN pour l'enregistrement du sous-domaine et ce qu'il est possible de faire pour la redirection. J'attends sa confirmation pour faire les modifications dans le code.

**Comment by alhyss** [comment]
Ah, ça fait écho au fait qu'actuellement le préfixe que j'utilise pour l'espace de nommage `http://snum.scenari-community.org/Metadata/Vocabulaire/#` est `snum`. J'avais fait ce choix il y a très longtemps et de manière assez arbitraire, notamment parce que nous n'avions alors pas de nom définitif pour l'application. Ça laissait accessoirement la possibilité d'utiliser le même espace de nommage pour des projets du SNUM sans rapport avec Plume.

Ces préfixes apparaissent : 
- dans le schéma des métadonnées communes. C'est du turtle, donc l'en-tête définit des préfixes pour les espaces de nommage, ce qui permet ensuite d'alléger le code. Dans l'en-tête, on aura `@prefix plume: <http://registre.data.developpement-durable.gouv.fr/plume/> .`, ce qui permettra ensuite d'écrire `[] plume:isExternal true` au lieu de `[] <http://registre.data.developpement-durable.gouv.fr/plume/isExternal> true` ;
- dans le code de Plume. Afin d'éviter d'avoir des URL qui traînent partout, il y a un module dans lequel tous les espaces de nommage sont déclarés une bonne fois pour toute en utilisant ces préfixes ;
- dans les modèles de formulaire. J'ai préféré utiliser la forme préfixée pour les identifiants des catégories de métadonnées, qui est quand même beaucoup moins lourde que des URI complètes.

Avec `http://registre.data.developpement-durable.gouv.fr/plume/`, il ne sera plus question d'utiliser l'espace de nommage pour autre chose que des identifiants de Plume. Donc choisir `plume` comme préfixe me semble assez naturel.

Est-ce que ça te paraît plus clair ou est-ce que je n'ai pas compris la question ?

**Comment by GilGuillouet** [comment]
Ok merci je n'étais pas dans la même optique, je pensais au sous-domaine. Ce qui m'avait choqué c'était que tu parles de préfixe Plume alors que pour moi on avait adopté le préfixe Registre... C'est bien le préfixe dans le nouvel espace de nommage.

**Comment by alhyss** [comment]
Oui, rien à voir avec le nom du sous-domaine, le préfixe que j'évoquais correspond plutôt à un alias / un diminutif de l'espace de nommage.

**Comment by alhyss** [comment]
Le changement d'espace de nommage est effectif ! En principe c'est bon partout : dans le code de Plume et *PlumePg* (**à réinstaller sur les bases de test**, donc), dans la documentation technique, etc.

Les classes et propriétés spécifiques de Plume utilisent désormais l'espace de nommage `http://registre.data.developpement-durable.gouv.fr/plume/` (préfixe `plume`) au lieu de `http://snum.scenari-community.org/Metadata/Vocabulaire/#` (préfixe `snum`).

L'objet `Namespace` correspondant définit par le  module `plume.rdf.namespaces` - et réutilisé par de nombreux autres modules - est par conséquent nommé `PLUME` au lieu de `SNUM`.

Les URI des concepts et ensembles de concepts créés par Plume sont également modifiés. Ils sont de la forme : 
- `http://registre.data.developpement-durable.gouv.fr/plume/[identifiant de l'ensemble]` pour les ensemble de concepts (`skos:ConceptScheme`) ;
- `http://registre.data.developpement-durable.gouv.fr/plume/[identifiant de l'ensemble]/[identifiant du concept]` pour les concepts (`skos:Concept`).

@WREATCHED Continuer à utiliser tes anciens JSON-LD pour les tests ne devrait pas provoquer d'erreur, mais tu vas perdre quelques informations dans la bataille... Si tu veux des commentaires PostgreSQL avec des métadonnées propres, tu peux copier le contenu des fichiers qui se trouvent dans [/plume/pg/tests/samples](https://github.com/MTES-MCT/metadata-postgresql/tree/main/plume/pg/tests/samples). J'attends que tu me confirmes que tout est en ordre de ton côté pour fermer l'issue.

**Comment by alhyss** [comment]
Pour le moment nous sommes sur une version alpha du registre, qui ne pointe pas encore sur le domaine cible `http://registre.data.developpement-durable.gouv.fr`, mais l'applicatif développé par Benoît David est opérationnel et son alimentation via l'API est outillée par le module [`admin.register`](https://mtes-mct.github.io/metadata-postgresql/reference/admin.register.html).

Bref, tout est prêt.

**Comment by alhyss** [comment]
Je clos l'issue puisque ce qui devait être fait pour la version 0.3 bêta est réalisé. Le sujet de l'hébergement est renvoyé à la version 1.0 - cf. issue #32.
