### ISSUE TITLE
Rafraîchissement du canevas lorsque Plume modifie l'emprise

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#35]
Lorsque j'active le zoom automatique sur les géométries visualisées, j'ai des effets indésirables avec les autres couches affichées dans le canevas : 
- lorsque le zoom augmente l'échelle, je me retrouve avec un affichage pixelisé des géométries de mes couches visibles ;
- lorsque le zoom déplace l'emprise, je ne vois pas les géométries ou parties de géométries qui étaient auparavant hors cadre.

Autrement dit, le genre de chose qui arrive quand le canevas n'est pas rafraîchi après une modification d'emprise. J'imagine que l'ajout d'une commande `self.canvas.redrawAllLayers()` (ou autre méthode que tu jugeras mieux adaptée) dans la fonction d'initialisation de `plume.bibli_plume_tools_map.GeometryMapToolShow` pourrait régler ça ?

Ce qui m'étonne un peu, c'est que je ne me rappelle pas avoir vu d'effet similaire dans tes vidéos et démos en direct. Mais je n'ai peut-être juste pas fait attention. Quoi qu'il en soit, j'ai constaté ça sur QGIS 3.16, et si jamais tu veux mes paramètres de rendu, n'hésite pas à demander.

**Comment by WREATCHED** [comment]
OK, implémenté
