### ISSUE TITLE
Bouton de verrouillage sur une couche ?

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#36]
Il me semblerait intéressant d'avoir dans la barre de menu de Plume un bouton de verrouillage qui bloque l'affichage sur la fiche de métadonnées courante quelles que soient les actions de l'utilisateur dans l'explorateur et le panneau des couches.

Cela permettrait à l'utilisateur de se référer à une fiche de métadonnées tout en paramétrant ses couches,  plutôt que d'être obligé d'y revenir à chaque fois qu'il manipule une autre couche (Plume basculant alors sur les métadonnées de ladite couche). Je pense que ce serait un vrai plus.

Est-ce que ce serait compliqué à implémenter ?

**Comment by WREATCHED** [comment]
L'idée est de créer un bouton "magique" de verrouillage et déverrouillage
Si verrouillé,  alors Plume ne prend plus en compte les interactions avec le gestionnaire de couche et le panneau explorateur
Afficher dans la barre de titre de la boite de dialogue principale "Plume | nom_du_schema.nom_de_la_table nom_attribut_geometrie"

**Comment by WREATCHED** [comment]
**Réponse en vidéo**
https://user-images.githubusercontent.com/66324136/161704992-114fdbc5-a93c-4a46-8f17-c438f10bee0b.mp4

**Comment by alhyss** [comment]
Ça m'a l'air super !

Comme il faut bien que je trouve à pinailler : 
- Je préférerais le fond brun très clair habituel pour montrer que le verrouillage est actif. D'une part parce qu'avec le rouge actuel ce n'est pas lisible, et d'autre part parce que je ne pense pas que l'information "verrouillage actif" soit réellement plus importante que "mode édition actif".
- Nous avions parlé de toujours afficher le nom de la couche dans le titre du panneau, même quand le verrouillage n'est pas actif, et voir la vidéo m'a convaincu que ce serait mieux. Même sans verrouillage on peut avoir besoin de se rappeler sur quelle couche on vient de cliquer, et cela peut aussi servir d'alerte si on a changé de couche sans s'en rendre compte. Dans ce cas, on pourrait  conserver le numéro de version : "_Plume v0.3.2 bêta | Couche mon_schema.ma_table (ma_geometrie)_".

Pour l'icône, tu as fait un SVG ? À la qualité de la vidéo près, elle me semble bien.

**Comment by WREATCHED** [comment]
- For the pinailleuse

Oui, j'ai fait un SVG pour l'icône du cadenas

**Résultat**

![image](https://user-images.githubusercontent.com/66324136/161722686-2d35ef3e-4c91-4489-9f74-15ee5f1d56ee.png)

**Comment by alhyss** [comment]
C'est bizarre d'avoir la version seulement quand le verrouillage n'est pas actif. Soit tout le temps, soit jamais me semblerait mieux (puisqu'elle apparaît quand aucune couche PostgreSQL n'est sélectionnée de toute façon). Accessoirement, c'est une amélioration fonctionnelle (et pas la seule en stock) donc elle ira dans Plume 0.4.0, tu peux d'ores-et-déjà mettre ce numéro dans tes métadonnées. Il n'y aura certainement pas de 0.3.3 sauf horrible bug signalé dans les jours qui viennent.

Sinon, je n'aimais pas tellement "verrou sur". Pour nous ça semble clair, mais en fait le verrouillage ne porte pas sur la couche mais sur la fiche de métadonnées affichée par Plume. Mieux vaudrait ne rien écrire qui pourrait suggérer que Plume "bloquerait" la couche elle-même, au risque que l'utilisateur se pose des questions du genre "ai-je le droit de modifier les données de ma couche ?". Si tu ne veux pas de "Couche" comme je le proposais, alors mieux vaut peut-être ne rien mettre : "_Plume | mon_schema.ma_table (ma_geometrie)_". Gagner de la place n'est pas plus mal et l'information sur l'état de verrouillage est déjà portée par le bouton.

D'ailleurs, je n'avais pas fait trop attention aux infobulles, mais toujours dans la même idée.
- Verrouillage désactivé : "_Verrouiller l'affichage sur la fiche de métadonnées courante._"
- Verrouillage activé : "_Déverrouiller l'affichage._"

**Comment by WREATCHED** [comment]
Tiens il y avait longtemps
Euh sinon c'est bien ?

La version, elle est derrière PLUME

![image](https://user-images.githubusercontent.com/66324136/161738452-f4f2ea41-0acd-4699-8043-b142f94e265c.png)

**Comment by alhyss** [comment]
Ah, désolée, je n'étais pas claire avec les infobulles. C'était juste le contenu des guillemets que je voulais mettre. Et pas la peine de citer le nom de la couche dans l'infobulle alors qu'il apparaît déjà dans le titre du panneau.

**Comment by WREATCHED** [comment]
Pinailleuse c'est féminin ou leslien

**Comment by WREATCHED** [comment]
![image](https://user-images.githubusercontent.com/66324136/161759373-890b3a51-f886-48cb-9956-692a367014d0.png)
