### ISSUE TITLE
Sélection d'une donnée autre que celle d'une base PostgreSQL / PostGIS

### ISSUE THREAD

**Issue by WREATCHED** [MTES-MCT/metadata-postgresql#41]
**Demande de la DDTM 40 :**
> Dans le cas où je sélectionne une donnée autre que celles de la base Postgis, la fiche de métadonnées retranscrit toujours les métadonnées de l'ancienne couche (Postgis) sélectionnée dans le panneau des couches.
J'aurais préféré que Plume n'affiche rien dans ce cas, ou le message par défaut en accueil de Plume serait parfait (de mon point de vue) : "Sélectionnez une couche PostgreSQL [...]"
Pourquoi? : Je me suis retrouvé à consulter des métadonnées non en cohérence avec la donnée sélectionnée et cela peut-être perturbant si on a que le catalogue d'attribut en visuel...

**Comment by WREATCHED** [comment]
Oui, c'est une bonne idée.
Nous avons prévu d'implémenter un bouton de verrouillage qui serait un complément de réponse

**Comment by alhyss** [comment]
Tout à fait d'accord, ça devient particulièrement pertinent en accompagnement du bouton de verrouillage (cf. issue #36). De cette façon : 
- le comportement par défaut de Plume sera de n'afficher les métadonnées de la couche que tant qu'elle est sélectionnée ;
- si l'utilisateur a besoin de figer l'affichage de Plume sur les métadonnées d'une couche pendant qu'il en manipule d'autres (PostgreSQL ou non), il pourra choisir d'activer le bouton de verrouillage.

Comme proposé, il me semblerait adapté de revenir sur le visuel d'accueil de Plume lorsque l'utilisateur sélectionne une couche dont le fournisseur n'est pas PostgreSQL. Je ne vois pas d'intérêt à prévoir autre chose.

**Comment by WREATCHED** [comment]
**Réponse en vidéo pour l'issue 41**

https://user-images.githubusercontent.com/66324136/161537182-6de6947b-bad3-498d-bac5-f53cc939e54f.mp4

**Comment by alhyss** [comment]
Je laisse @StormKlaus confirmer s'il le souhaite, mais ça me semble être le bon comportement quand la fiche de métadonnées n'est pas verrouillée.

**Comment by StormKlaus** [comment]
Je confirme que c'est le comportement souhaité, merci !
_(quand la fiche de métadonnées n'est pas verrouillée)_
