### ISSUE TITLE
Adaptation du curseur au survol des hyperliens

### ISSUE THREAD

**Issue by WREATCHED** [MTES-MCT/metadata-postgresql#43]
**Demande de la DDTM 40 :**
> Au survol des liens/URL on a l'habitude que le curseur de la souris se transforme en main...

**Comment by alhyss** [comment]
Mais n'est-ce pas le cas ?

![curseur_hyperlien](https://user-images.githubusercontent.com/55992003/160900738-6c7ba86f-2c5d-471a-9648-4f1d047575ae.png)

La capture est du QGIS 3.16, mais j'ai la même chose avec la 3.10 et la 3.22.

À moins qu'il soit question d'autres hyperliens ? S'il s'agit du mode édition, alors le curseur n'est effectivement pas modifié au survol des URL, mais c'est cohérent avec le fait qu'elles ne sont pas cliquables.

**Comment by WREATCHED** [comment]
Pas tout à fait Leslie,
Ok si on ne manipule pas les géométries sur le Canvas.
Par contre si on les manipule, je reste sur le pointeur de souris,
Il faut que je revois le mécanisme de saisie, juste pour la matérialisation du pointeur de souris

**Comment by WREATCHED** [comment]
**Corrigé :** 
Réinitialisation des comportements par défaut du pointeur de souris pour l'ensemble des widgets après avoir utilisé les outils de géométries

**Comment by StormKlaus** [comment]
C'est un comportement que j'observe également dans les URL retranscrit en résultat d'interrogation spatiale (Outil Identifier les données) de QGIS. Mon curseur ne se transforme pas en main au survol des URL retranscrits dans les attributs du panneau.
Donc ce n'est pas un comportement propre à plume, mais plutôt à QGIS... voir peut-être propre à mon poste informatique.

C'est une issue à laquelle il ne faut donc pas donner suite.

**Comment by alhyss** [comment]
@StormKlaus C'est surprenant ! Je ne reproduis pas non plus l'effet avec *Identifier les données* sous QGIS 3.16.4.

Ceci dit, ta remarque s'appliquait bel et bien à Plume. Comme l'indiquait @WREATCHED ci-avant, Plume change la forme du pointeur lors de l'utilisation des outils de saisie manuelle des géométries, et il ne fallait pas seulement lui rendre sa forme originale, mais le réinitialiser (avec [`QGuiApplication.restoreOverrideCursor`](https://doc.qt.io/qtforpython-5/PySide2/QtGui/QGuiApplication.html#PySide2.QtGui.PySide2.QtGui.QGuiApplication.restoreOverrideCursor)) pour que le curseur s'adapte de nouveau au contexte - comme le fait de se transformer automatiquement en petite main au survol d'un hyperlien.

Je clos le ticket vu que ce petit dysfonctionnement est corrigé dans la v0.3.2 bêta, mais ça n'empêche pas d'ajouter des commentaires à l'issue si tu le souhaites.

**Comment by StormKlaus** [comment]
@alhyss Je confirme, effectivement c'était bien un comportement hérité de Plume, le passage à la v0.3.2 bêta a corriger ce comportement.
Le curseur de ma souris se transforme désormais bien en main au survol des liens dans la panneau plume ou encore de celui en résultat d’ Identifier les objets.

Merci !
