### ISSUE TITLE
Avertir l'utilisateur si on quitte le mode édition en n'ayant pas sauvegardé ses modifications

### ISSUE THREAD

**Issue by FERRATON** [MTES-MCT/metadata-postgresql#46]
A priori si on quitte le mode édition sans avoir sauvegardé ses modifications, on les perd sans message d'alerte.

**Comment by alhyss** [comment]
Effectivement, c'est le comportement actuel : 
- Le crayon ![read](https://user-images.githubusercontent.com/55992003/161245696-cf1fbb1c-f0f7-4c6e-9a29-a08301e87f75.svg) ne sert qu'à activer ou désactiver le mode édition.
- Seule la disquette ![save](https://user-images.githubusercontent.com/55992003/161245832-ad8c94e5-f4f1-49a4-9ca9-0964b20e6505.svg) permet d'enregistrer.

A minima, je pense qu'on peut ajouter un avertissement dans l'infobulle du crayon (version mode édition actif), qui indique seulement _"Quitter le mode édition"_, à ce stade. Quelque chose du genre _"Quitter le mode édition. Attention : les modifications non enregistrées seront perdues."_.

Le niveau supérieur serait d'avoir une boîte de dialogue de confirmation, qu'on ferait soit apparaître systématiquement, soit (avec un peu plus de travail et en admettant quelques faux positifs) uniquement quand il y a effectivement eu des modifications. L'avantage est que ça ressemblerait à ce dont les utilisateurs ont l'habitude avec le mode édition sur les couches de QGIS, l'inconvénient est que c'est plus lourd.

Je proposerais bien de soumettre ça au sous-groupe Métadonnées, sauf à décider tout de suite qu'on part sur un compromis :  implémenter la boîte de dialogue, tout en permettant de la désactiver via un paramètre utilisateur ? Qu'en penses-tu @WREATCHED ?

**Comment by WREATCHED** [comment]
Oui, oui , même réponse que sur l'issue #47

**Comment by WREATCHED** [comment]
![image](https://user-images.githubusercontent.com/66324136/161524955-86b42b1d-13ee-4a14-8283-547762dab427.png)

**Comment by alhyss** [comment]
Une bonne première étape !

Pour la future boîte de dialogue de confirmation, j'ai ajouté un attribut `plume.rdf.widgetsdict.WidgetsDict.modified`. Il faudra demander une confirmation avant de quitter le mode édition si le paramètre utilisateur permettant d'inhiber ces messages ne vaut pas `True`  et si l'une des deux conditions suivantes est remplie : 
- `widgetsdict.modified` vaut `True`.
- Parmi les clés du dictionnaire de widgets correspondant à des widgets de saisie, il en existe au moins une telle que la valeur saisie dans le widget est différente de celle contenue dans la clé `'value'` du dictionnaire interne.

J'ai mis quelques mots là-dessus dans la [documentation technique](https://mtes-mct.github.io/metadata-postgresql/usage/actions_generales.html#caracteristiques-du-bouton).

**Comment by WREATCHED** [comment]
Peux-tu me confirmer cette boite de dialogue, enfin son texte
![image](https://user-images.githubusercontent.com/66324136/161775849-a5ea5ea3-7876-4d9f-8068-6760b506501b.png)

**Comment by WREATCHED** [comment]
**Réponse en vidéo**

https://user-images.githubusercontent.com/66324136/161781134-1e703918-425b-47c6-8990-66a7894dfb7e.mp4

**Comment by alhyss** [comment]
Pour la boîte de dialogue, je proposerais bien : 
```
Si vous poursuivez, les modifications non enregistrées seront perdues.
| Confirmer |    | Annuler |
```

Sinon, ça demanderait davantage d'ajustements de ton côté, mais on aurait pu imaginer un message à la QGIS : 
```
Voulez-vous enregistrer les modifications ?
| Enregistrer |    | Ne pas tenir compte |    | Annuler |
```

Je ne pousse pas spécialement pour cette seconde option, les deux me semblent correctes. Avec la première les utilisateurs vont vite s'habituer à enregistrer avant de chercher à quitter.

Pour les paramètres avancés, je pense qu'il faut préciser un peu de quel "message d'avertissement" on parle. Peut-être : "_Ne pas afficher d'avertissement à la sortie du mode édition_" ?

Sans rapport, mais pourrais-tu en profiter pour supprimer de la liste le paramètre "_Préparer les métadonnées pour la réplication vers GéoIDE_" ? Il n'est pas utilisé actuellement et sa présence pourrait donner de fausses idées...

**Comment by WREATCHED** [comment]
1. Pour la boite de dialogue : 

- Libellé OK
- Je peux utiliser les enum des boutons suivants qui correspondent à ce que tu veux.

Peut-être serait-il souhaitable de modifier le libellé pour l'adapter ?
**Version 1**
![image](https://user-images.githubusercontent.com/66324136/161904436-e4899c7b-56da-4887-b244-12c8bf6fdbbb.png)
**Version 2**
![image](https://user-images.githubusercontent.com/66324136/161903835-19dc1423-a9bd-456b-bca9-375a462289a4.png)

2. Pour l'option "GéoIDE" OK

**Comment by alhyss** [comment]
Je ne pense pas qu'il soit nécessaire de personnaliser les libellés des boutons. Tel que tu le proposes, ça me semble déjà suffisamment clair.
Merci pour les modifs sur les paramètres avancés !

**Comment by WREATCHED** [comment]
![image](https://user-images.githubusercontent.com/66324136/161965955-2d30793a-7b5c-40dc-82f4-6362e59993a7.png)
