### ISSUE TITLE
ne pas permettre de changer de couche quand on est en mode modification

### ISSUE THREAD

**Issue by FERRATON** [MTES-MCT/metadata-postgresql#47]
Si on est en mode modification des métadonnées sur une couche et que l'on change de couche on perd ses modifications sans message d'erreur ou d'alerte

**Comment by alhyss** [comment]
Il me semble que ça rejoint la question du bouton de verrouillage, qui fait partie des petites améliorations fonctionnelles restant à implémenter - cf. issue #36. Nous l'avions surtout évoqué en ayant en tête le mode lecture, mais il devrait être activé par défaut en mode édition (voire ne pas être désactivable). Tu es d'accord avec ça, @WREATCHED ?

**Comment by WREATCHED** [comment]
https://user-images.githubusercontent.com/66324136/161423292-1180199e-c6c2-4475-936f-f9aa45f5d3df.mp4

**Comment by FERRATON** [comment]
![image](https://user-images.githubusercontent.com/2129643/161426343-e63d7b58-440f-4622-b9cf-5b22161ec587.png)

**Comment by alhyss** [comment]
Bonjour à tous les deux,
Je n'aime pas trop ce fonctionnement. Les messages sont lourds et, si on les désactive, on revient au problème initial. De plus, dans les deux cas l'utilisateur n'est pas libre de manipuler les couches dans son explorateur sans interférence de Plume (l'ouverture des boîtes de dialogue est même encore plus gênante que la situation actuelle de ce point de vue).
Il me semblerait préférable de gérer ça dans le cadre du verrouillage - issue #36 -, avec en mode édition un verrouillage activé par défaut et non désactivable qui fera que les actions de l'utilisateur dans le panneau des couches et l'explorateur n'affecteront pas Plume. Dans ce cas il n'y aura évidemment pas lieu d'afficher un quelconque message.
