### ISSUE TITLE
Contrôle de la version de PlumePg et des droits sur ses objets

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#49]
La prochaine version de Plume va aller de paire avec une nouvelle version de PlumePg et ne sera pas compatible avec les versions antérieures.

Pour l'heure, Plume se contente de [vérifier que PlumePg est installée](https://mtes-mct.github.io/metadata-postgresql/usage/modeles_de_formulaire.html#presence-de-l-extension-plumepg) avant d'aller récupérer ses modèles, mais il faudra dorénavant vérifier aussi que la version installée est compatible avec la version de Plume dont dispose l'utilisateur.

Il y a aura clairement une condition du type "version de PlumePg supérieure ou égale à la version de référence x.x.x", mais je pense aussi qu'on aurait intérêt à fixer une borne supérieure, car je ne suis pas sûre qu'on sera toujours capable de garantir la rétro-compatibilité.

Par ailleurs, il serait utile de vérifier également si l'utilisateur a bien les droits nécessaires sur les objets de l'extension : `USAGE` sur le schéma et `SELECT` sur les tables et vues. Si Asgard était actif sur la base au moment de l'activation de PlumePg, c'est normalement le cas, mais Asgard n'est pas présent sur toutes les bases... Il me semblerait plus propre d'en rester aux modèles locaux quand l'utilisateur n'a pas accès aux données, plutôt que d'avoir le genre d'erreur que j'ai eu lors de la démonstration. D'autant que, en pratique, une telle erreur empêcherait l'utilisateur de se servir de Plume jusqu'à ce qu'une personne habilitée lui donne les droits.

Bref, je vais préparer une requête qui réalise tous ces tests.

**Comment by WREATCHED** [comment]
**Réponse**
![image](https://user-images.githubusercontent.com/66324136/166154128-c63eed80-d7a4-4bbd-9971-6a6807f942ee.png)

**Ok / Ko** ?

**Comment by WREATCHED** [comment]
![image](https://user-images.githubusercontent.com/66324136/166249586-cffeb02e-bc7b-4e3a-a3b2-bc92eb5e0695.png)

**Comment by WREATCHED** [comment]
euh ça commence par c et se termine par un e

**Comment by alhyss** [comment]
Je viens de tester avec PlumePg 0.0.1, qui n'est donc plus compatible avec la v0.4 bêta, et le texte est tronqué au milieu d'une phrase : 

![compatibilite_plume_pg](https://user-images.githubusercontent.com/55992003/167441567-39daa55a-473b-4e71-a614-40ff1d6bd2cd.png)

Le caractère suivant est `<`, qui ne passe pas évidemment pas en HTML...

Tu voudras peut-être le gérer autrement, mais j'ai pu confirmer que le texte s'affiche correctement en échappant la variable `pb` de `plume.plume_ui.Ui_Dialog_plume.displayToolBar`, soit en remplaçant ça : 
```python
mTextToolTip += "<br><br><i>NB : Vous n'avez accès qu'aux modèles pré-configurés standards. "  + pb + "</i>"
```
par ça : 
```python
mTextToolTip += "<br><br><i>NB : Vous n'avez accès qu'aux modèles pré-configurés standards. " \
    + escape(pb) + "</i>"
```

Avec l'import suivant dans l'en-tête : 
```python
import escape from html
```
