### ISSUE TITLE
Traduction de Plume (Anglais/Français)

### ISSUE THREAD

**Issue by WREATCHED** [MTES-MCT/metadata-postgresql#50]

**Comment by WREATCHED** [comment]
Plume devrait pouvoir être traduit dans la langue de Shakespeare
Les `QtWidgets.QApplication.translate("colorbloc_ui", "myMessEnglish", None)` sont déjà dans le code.

- Traduction du fichier plume_fr.ts

_Exemple_ : 
![image](https://user-images.githubusercontent.com/66324136/161970880-2fbfcbd9-1035-45d9-a4ba-02c74d124676.png)

**Comment by WREATCHED** [comment]
**Réponse en vidéo**
https://user-images.githubusercontent.com/66324136/163541445-85793fc7-b019-42f1-bd4b-44f897cd710a.mp4

@alhyss, J'ai comme tu peux le constater, géré le multi-langage
Toutefois, on peut voir que TOUT n'est pas traduit par exemple, le titre des QGroupBox et/ou encore les info-bulles
C'est de ton coté (mécanisme) et je ne sais pas si tu veux aller jusque là par exemple, à gérer cela de ton coté ex : envoyer un tuple avec un dictionnaire ```( { langue : "libelle de la langue" } )``` => ```( { "fr": "Ajouter un élément", "en" : "Add Item" }, ......)```
Aucune priorité bien évidemment,
Une question : marques-tu "Résolu", à toi de voir

**Comment by alhyss** [comment]
Hmm...

Honnêtement, ça représenterait sans doute pas mal de travail de mon côté pour articuler ça proprement avec le reste, sans parler du temps nécessaire pour écrire toutes les traductions. Je ne sais pas, d'ailleurs, si c'est moi qui te remonterais toutes les traductions comme tu l'évoques, ou si ce ne serait pas plutôt à toi de fournir en argument au constructeur de `plume.rdf.widgetsdict.WidgetsDict` la langue attendue pour la coquille du formulaire, comme tu le fais déjà pour son contenu avec le paramètre `language`. À première vue, je pense que la seconde option serait plus pratique pour moi, et en plus il n'y aurait quasi rien à changer de ton côté.

En tout cas, je préfère ne pas me lancer là-dedans pour la v1.0, sachant qu'elle s'adresse avant tout à nos services, pour lesquels une traduction anglaise incomplète de l'interface ne devrait pas poser problème.

Si ça te va, tu peux marquer l'issue comme résolue et la flécher sur la v0.4 bêta. Je vais aller ajouter ça à la liste de l'issue #19 pour qu'on garde le sujet en tête, et on ré-ouvrira une issue si on décide un jour qu'il y a lieu de s'y attaquer.

**Comment by WREATCHED** [comment]
OK 👍

**Comment by WREATCHED** [comment]
J'ai oublié de montrer le About
![image](https://user-images.githubusercontent.com/66324136/163568060-d70d66fb-c719-4dcd-adf6-0cb1c8059195.png)

**Comment by alhyss** [comment]
Tant que tu y es, il y aurait peut-être quelques éléments à actualiser là-dedans ? 
- À la toute fin du troisième paragraphe, il est encore marqué `metadata` pour le nom de l'extension PostgreSQL au lieu de PlumePg/`plume_pg`.
- Dans le dernier paragraphe, ce n'est plus `bibli_rdf` et `bibli_pg` mais `plume.rdf`, `plume.pg` et `plume.iso`.

**Comment by WREATCHED** [comment]
**OK** y compris in English
![image](https://user-images.githubusercontent.com/66324136/163571396-390c269c-fdf9-438a-ab7e-0e47239f22ab.png)

**Comment by alhyss** [comment]
Merci :)
