### ISSUE TITLE
installation pénible

### ISSUE THREAD

**Issue by FERRATON** [MTES-MCT/metadata-postgresql#51]
Lors de la première utilisation Plume cherche à installer des bibliothèques python.
La console qui s'ouvre est déroutante car les temps d'attentes sont très longs... voir en PJ les nombreux essais avec timeout...
Je me doute que ce n'est pas si facile, mais il y a peut-être possibilité d'optimiser un peu...
Au minimum peut-être mettre un message d'avertissement indiquant que les temps peuvent être longs...
Peut-être ne pas insister après un premier timeout ?
A voir ce qui peut-être fait...
Bonne journée
Alai
![timeout_plume](https://user-images.githubusercontent.com/2129643/162134684-dcec91c5-eaab-4ae9-8458-adb99ff62ccc.png)
n

**Comment by alhyss** [comment]
Les timeout interviennent sur la tentative de mise à jour de `pip`, en fait, pas sur l'installation des bibliothèques. `pip` a une option [`--retries` ](https://pip.pypa.io/en/stable/cli/pip/#cmdoption-retries) pour contrôler le nombre de tentatives, et on pourrait effectivement se contenter d'un essai. Peut-être qu'utiliser [`--quiet`](https://pip.pypa.io/en/stable/cli/pip/#cmdoption-q) pour ne pas afficher les avertissements qui risquent d'inquiéter inutilement l'utilisateur serait également une bonne chose.

**Comment by WREATCHED** [comment]
Je confirme que ce n'est pas l'installation des bibliothèques, puisqu'elles se font maintenant en local et très rapidement, ce qui est un plus.
J'ai souhaité puisque cela se produit parfois, la mise à jour de PIP qui lui nécessite une connexion internet.
Encore une fois, c'est pour de la robustesse et dire que c'est pénible, c'est un peu exagéré.
**Solution**, 

- J'enlève la maj de pip et plus de pb, mais on risque une non mise à jour si PIP n'est pas upgradé
- Utiliser l'option --retries comme le préconise Leslie ce qui me semble très bien

Concernant l'outil, tu ne nous a pas fait de retour @FERRATON

**Comment by WREATCHED** [comment]
Corrigé pour la version 0.3.4 Bêta poussé sur le Git

**Comment by FERRATON** [comment]
Perso je ne ferais pas la mise à jour de pip. Sinon il est peut-être possible de récupérer les paramètres de proxy pour les ajouter dans la commande de mise à jour ? (pas eu le temps de regarder le code pour voir si tu le fais déjà, je suis en visio ce matin)...
Sinon pour un retour sur l'outil je n'ai pas fait de retour, mais pas besoin je pense.... l'outil à atteint un niveau de sophistication que je n'avais pas imaginé lorsque j'ai fait le proto...donc 
![image](https://user-images.githubusercontent.com/2129643/162158058-90e66c8b-d4a1-410a-a949-5d2076595a94.png)

**Comment by alhyss** [comment]
@WREATCHED Un timeout de 2 secondes est peut-être un peu violent ? S'il n'y a qu'un seul essai, on peut peut-être laisser 5 secondes au serveur pour répondre ?

La tentative de mise à jour de `pip` me semble une bonne chose, surtout avec les vieilles versions de QGIS qui peuvent traîner des versions de `pip` sérieusement obsolètes. On peut espérer qu'elle ne soit pas nécessaire et que même les vieux `pip` installeront correctement nos bibliothèques (on compte même dessus pour les installations sans accès internet), mais je ne vois pas d'effet négatif potentiel à faire la mise à jour lors de l'installation.

**Comment by FERRATON** [comment]
Le principal inconvénient selon moi est que la commande sans l'option --proxy risque de ne jamais fonctionner dans les services.

**Comment by alhyss** [comment]
En télétravail sans VPN ça marche :)
