### ISSUE TITLE
Afficher plus clairement le nom du modèle courant

### ISSUE THREAD

**Issue by PascalAstruc** [MTES-MCT/metadata-postgresql#55]
Pour les modèles , le concept me parait intéressan,t ce serait bien d'avoir sur l'interface l'info sur le modèle actif sans aller dans le menu déroulant (pas intuitif et c'est surtout important car les infos sont visible en fonction du modèle)
Merci

**Comment by WREATCHED** [comment]
![image](https://user-images.githubusercontent.com/66324136/163574741-3cd6daf9-11aa-4074-a873-7d263130ab4f.png)

**Comment by PascalAstruc** [comment]
C'est plutôt pas mal (c'est vrai il y a beaucoup de chose dans l'interface) en différenciant peut être italique gras et plus petit ou par l’alignement ou la couleur ou tout simplement en reprenant le visuel du menu présent dans le déroulant (histoire de hiérarchiser l'info).

**Comment by alhyss** [comment]
Comme tu t'en doutais, je n'aime pas 😄. C'est peu visible, s'il n'y avait pas le mot "modèle" dans le nom du modèle on ne saurait pas de quoi il s'agit... Tout ça serait sans doute améliorable par de la mise en forme, mais, surtout, le fait que ça apparaisse dans un onglet du formulaire alors que le modèle définit toute la structure du formulaire y compris les onglets eux-mêmes me paraît vraiment contre-intuitif.

Plus généralement, il me semble que la seule manière d'assurer que l'utilisateur comprenne ce qu'est cette information est de faire en sorte que le nom du modèle soit affiché à côté du menu qui permet de sélectionner le modèle. Je continue à penser que le mettre dans la barre d'outils sous une forme comparable à ce que tu as fait avec les langues est notre meilleure option. Quitte à faire deux lignes de barre d'outils pour avoir plus de place, ou à n'afficher le nom du modèle qu'au-delà d'un certain seuil de largeur de panneau/fenêtre.

Au fait, PlumePg limite à 48 caractères la longueur du nom d'un modèle, et ça ne me choquerait pas de tronquer les noms qui, par exemple, dépassent 20 caractères (voire moins).

```python
lim = 20
if len(t) > lim:
	t = '{}...'.format(t[:lim - 3])
```

**Comment by WREATCHED** [comment]
Vu le commentaire de Pascal, je propose qu'on le soumette au sous groupe méta ?

**Comment by WREATCHED** [comment]
![image](https://user-images.githubusercontent.com/66324136/163593125-401d660a-4172-464c-b1dc-51a4a93e21d3.png)

**Comment by WREATCHED** [comment]
![image](https://user-images.githubusercontent.com/66324136/163593397-9dfe6f5e-1c6a-4815-875e-eeeb760d15a3.png)

**Comment by WREATCHED** [comment]
![image](https://user-images.githubusercontent.com/66324136/163594308-18704161-c180-41ad-8f82-3f01c76acbb8.png)

**Comment by WREATCHED** [comment]
![image](https://user-images.githubusercontent.com/66324136/163594593-41f111d6-f2d3-4316-b6f3-ec89fb01182d.png)

**Comment by WREATCHED** [comment]
Dl : Tester QtoolButton Vs QComboBox pour visualisation

**Comment by WREATCHED** [comment]
**Réponse en vidéo et captures d'écrans**
https://user-images.githubusercontent.com/66324136/164049860-ab058717-7b55-43c0-a4e0-8ae7a642b1aa.mp4

![image](https://user-images.githubusercontent.com/66324136/164050428-7fcbf634-ee61-4385-a357-ea5200857a8d.png)

**Qu'en pensez-vous ?**

**Comment by PascalAstruc** [comment]
C'est parfait pour moi.
