### ISSUE TITLE
Permettre la sélection du texte en mode lecture

### ISSUE THREAD

**Issue by WREATCHED** [MTES-MCT/metadata-postgresql#56]
L'objectif est de permettre en mode lecture, la sélection et la copie du texte des zones d'information.

**Comment by WREATCHED** [comment]
**Réponse :** 
Sélection du texte avec la souris, possibilité de faire Ctrl+C ou Ctrl A et/ou menu contextuel

![image](https://user-images.githubusercontent.com/66324136/163327543-9248be11-6c0c-4df9-970b-8a4e9f2ca41a.png)

**Comment by alhyss** [comment]
C'est parfait ! Merci merci :)

**Comment by WREATCHED** [comment]
**RESOLU**
