### ISSUE TITLE
Impossible de supprimer PlumePg tant que QGIS est ouvert

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#63]
... dès lors que Plume a été lancé, et même s'il n'y a plus de fiche de métadonnée ouverte.

Il n'y a pas d'erreur, la commande `DROP EXTENSION plume_pg` paraît juste être mise en attente jusqu'à la fermeture de QGIS.

**Comment by WREATCHED** [comment]
La nouvelle gestion des connexions avec le Context Manager a résolu le problème
