### ISSUE TITLE
Uniformisation des requêtes PostgreSQL

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#69]
L'idée générale est de faire en sorte que toutes les fonctions du module `plume.pg.queries` puissent être appelées exactement de la même façon.

Tous les paramètres sont fournis à la fonction qui crée la requête. 
Par exemple, on aura désormais :
```python
query = query_is_relation_owner('nom du schéma', 'nom de la table')
```

La fonction renvoie un tuple, qu'on éclate pour le passer en argument de `psycopg2.cursor.execute` : 
```python
cur.execute(*query)
```

Antérieurement, certains paramètres étaient passés directement à `psycopg2.cursor.execute` plutôt qu'à la fonction elle-même, avec des comportements variables d'une fonction à l'autre. Les fonctions écrites récemment avaient déjà le fonctionnement décrit ci-avant, ce qui ajoutait encore un peu d'hétérogénéité à l'affaire.

Cette évolution va nécessiter de revoir les appels aux fonctions suivantes  : 
- [x] `query_is_relation_owner`
- [x] `query_exists_extension`
- [x] `query_get_relation_kind`
- [x] `query_update_table_comment`
- [x] `query_get_table_comment`
- [x] `query_list_templates`
- [x] `query_get_categories`
- [x] `query_template_tabs`
- [x] `query_get_columns`
- [ ] `query_update_column_comment` (je crois que celle-là n'est pas utilisée)
- [x] `query_update_columns_comments`
- [x] `query_get_geom_srid`
- [x] `query_get_geom_extent`
- [x] `query_get_geom_centroid`

À noter que pour certaines d'entre elles tous les paramètres sont déjà au bon endroit, il y aura juste l'astérisque à ajouter.

Le message d'erreur à afficher lorsque la requête était supposée renvoyer un résultat et ne le fait pas est fourni par l'attribut `plume.pg.queries.PgQueryWithArgs.missing_mssg` de la requête.

_@WREATCHED Attends mon feu vert pour appliquer les changements de ton côté, je suis en train d'écrire cette issue alors que je n'ai pas fini de modifier les fonctions._

**Comment by alhyss** [comment]
@WREATCHED C'est fait, tu peux y aller. Désolée d'avoir tant traîné !

En y repensant, je t'avais mis ci-dessus la liste des fonctions concernées, mais le plus simple est encore de faire une recherche sur `query_` dans tous tes fichiers. À l'exception des commandes d'import, ça te donnera exactement tous les endroits où tu auras des modifications à faire.

**Comment by WREATCHED** [comment]
- [ ] `query_evaluate_local_templates`

query_update_column_comment Oui, non utilisée

**Comment by WREATCHED** [comment]
Ok pour messages générés par les requêtes
Je pousse sur le GitHub
