### ISSUE TITLE
Import de métadonnées depuis un fichier XML INSPIRE

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#72]
*Demande émanant du sous-groupe Métadonnées du 12 mai 2022.*

De même que Plume propose aujourd'hui l'import de fichiers de métadonnées RDF (avec le vocabulaire DCAT), il s'agirait de proposer l'import d'un fichier de métadonnées INSPIRE/ISO 19115.

En arrière plan, cette fonctionnalité mêle les mécanismes d'import depuis un fichier (même type de source) et d'import depuis un service CSW (même format et mapping). 

Le menu d'import ![icône import](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/general/import.svg) proposerait trois items : 
```
Import depuis un fichier (DCAT)
Import depuis un fichier (INSPIRE)
Import depuis un service CSW (INSPIRE)
```
Pour la boîte de dialogue, le format attendu sera `xml (*.xml)`.

**Comment by alhyss** [comment]
@WREATCHED C'est bon de mon côté (quasi rien à faire dans le code, il faut dire, j'ai passé plus de temps sur la doc).

Pour l'implémentation dans l'interface, c'est comme l'import depuis un fichier DCAT, mais encore plus simple, car il n'y a pas de question à se poser sur le format. Cf. détails dans la [documentation technique](https://mtes-mct.github.io/metadata-postgresql/usage/actions_generales.html#import-de-metadonnees-depuis-un-fichier-inspire).

**Comment by WREATCHED** [comment]
**Réponse**
![image](https://user-images.githubusercontent.com/66324136/174734741-2fb428ad-3810-4ebf-87c8-36365178691a.png)

**Comment by alhyss** [comment]
Pour les infobulles : 

| Item | Texte de l'infobulle | Observations |
| --- | --- | --- |
| Bouton de la barre d'outil | *Importer les métadonnées.* | Autant faire simple, d'autant qu'on ajoutera certainement des modes d'import à court ou moyen terme (typiquement, pour DCAT, permettre à l'utilisateur de fournir une URL au lieu d'un fichier serait facile à faire...). |
| Menu `Import depuis un fichier (DCAT)` | *Importer le contenu d'un fichier de métadonnées utilisant une syntaxe RDF avec le vocabulaire DCAT. Le résultat sera d'autant plus concluant si les métadonnées sont conformes aux profils DCAT-AP v2 ou GeoDCAT-AP v2.*  | |
| Menu `Import depuis un fichier (INSPIRE)` | *Importer les métadonnées contenues dans un fichier XML conforme aux spécifications INSPIRE.* | |
| Menu `Import depuis un service CSW (INSPIRE)` | *Importer des métadonnées conformes aux spécifications INSPIRE en interrogeant un service CSW.* | |

Pour les deux boîtes de dialogue d'import depuis un fichier, est-ce que ce ne sera pas plus logique qu'elles aient le même titre que l'item du menu, donc *Import depuis un fichier (INSPIRE)* et *Import depuis un fichier (DCAT)* ? Je n'y avais pas du tout réfléchi jusque-là, mais je me dis en tout cas que nous aurions intérêt à éviter d'utiliser l'expression "fiche de métadonnées" pour désigner ces fichiers. Mieux vaut réserver ce nom aux métadonnées que l'utilisateur voit dans l'interface de Plume, sinon nous allons créer de la confusion.

Pour la liste de sélection des formats côté INSPIRE, je préfèrerais `XML (*.xml)` et `Tous les fichiers (*.*)`. Ce sont uniquement les libellés qui changent, tes filtres font exactement ce qu'il faut ! Le truc, c'est que dans les deux cas ce qu'on attend est un fichier XML conforme aux spécifications d'INSPIRE (toujours des *"Fichiers INSPIRE"*, donc). On admet seulement que ce fichier puisse ne pas avoir pour extension `.xml`.

**Comment by WREATCHED** [comment]
Je pense que c'est OK

**Comment by alhyss** [comment]
Yep ! Merci ! Ça m'a l'air tout bon sauf une petite coquille sur le titre de la boîte de dialogue pour l'import depuis un fichier DCAT. C'est *"... (DCAT)"* et pas *"... (DACT)"*.

**Comment by WREATCHED** [comment]
Ah !! dyslexie quand tu nous tiens ....
![image](https://user-images.githubusercontent.com/66324136/174806749-f7baf1cc-a589-49aa-b9a9-6a6e8c7c440a.png)

**Comment by alhyss** [comment]
Eh bin ça m'a l'air parfait !
