### ISSUE TITLE
Installation des dépendances de Plume dans plusieurs versions parallèles de QGIS

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#76]
Plusieurs applications QGIS installées en parallèle ou successivement sur un poste partagent leur fichier de configuration `QGIS3.ini` et leurs plugins, mais pas nécessairement leurs dépendances python. Celles-ci doivent être installées et mises à jour indépendamment : 
* pour chaque version de python utilisée par une ou plusieurs applications QGIS si l'installation des packages se fait dans les répertoires utilisateurs `C:\Users\%username%\AppData\Roaming\Python\{version de python}\site-packages` ;
* voire pour chaque application QGIS si l'installation est paramétrée pour s'effectuer directement dans le répertoire d'installation de QGIS. Par exemple `C:\Program Files\QGIS 3.22.8\apps\Python39\Lib\site-packages` pour un QGIS 3.22 installé sous `Program Files`.

Actuellement, le processus de mise à jour des dépendances de Plume est exécuté à chaque installation d'une nouvelle version de Plume. Plume utilise un paramètre de configuration du fichier `QGIS3.ini` pour tracer le fait que les dépendances ont été mises à jour et empêcher le processus de s'exécuter à chaque lancement de Plume... jusqu'à la mise à jour suivante du plugin.

```ini
[PLUME]
...
Generale\versionPlumeBibli=v0.5.0 b\xeata
```

*Si le numéro de version du paramètre `versionPlumeBibli` coïncide avec la version courante de Plume, les dépendances python sont considérées comme installées et à jour.*

Ce fonctionnement n'est pas viable lorsque plusieurs applications de QGIS ne partageant par leurs dépendances python sont utilisées sur un poste (usage parallèle ou remplacement par une version de QGIS plus récente), puisqu'après installation / mise à jour des dépendances pour l'une d'entre elles, Plume présumera à tort que les dépendances sont disponibles pour toutes. Ceci peut provoquer un plantage au lancement de QGIS ou à l'activation de Plume, avec un message d'erreur de cet ordre (cas où Plume n'accède à aucune de ses dépendances) : 
```
Impossible de charger l'extension 'plume' provoque une erreur lors de l'appel à sa méthode classFactory()
ModuleNotFoundError: No module named 'rdflib'
```

D'autres messages pourraient apparaître en cas de dépendances installées mais obsolètes par rapport aux exigences de Plume.

Méthode de dépannage : 
* Ouvrir le fichier de configuration de QGIS, `QGIS3.ini` de l'utilisateur, généralement accessible dans `C:\Users\%username%\AppData\Roaming\QGIS\QGIS3\profiles\default\QGIS` (en remplaçant le cas échéant `default` par le nom du profil utilisé).
* Supprimer la ligne du paramètre `Generale\versionPlumeBibli` et enregistrer.
* Relancer QGIS. Les dépendances s'installent alors normalement.

**Comment by alhyss** [comment]
Principe retenu pour la correction du problème, distinguer dans le `QGIS3.ini` le paramètre qui trace la version courante de Plume selon la version de QGIS. Le processus d'installation / mise à jour des dépendances sera alors exécuté une fois par version de QGIS après chaque installation / mise à jour de Plume.

**Comment by WREATCHED** [comment]
Corrigé sur la  version en cours 0.5.0 Bêta
![image](https://user-images.githubusercontent.com/66324136/183828401-b6170580-00f1-4015-8ba1-0f4af7b1c177.png)

**Comment by alhyss** [comment]
Super !

J'ai fléché ça sur la v1.0. Je ne pense pas que ça justifie en soi de sortir une version corrective, considérant qu'il y a une méthode de dépannage simple.

En y repensant, il y a tout de même des chances que certains de nos testeurs soient confrontés au problème. Peut-être que d'aucuns vont profiter de l'été pour passer de QGIS 3.18/python 3.7 à QGIS 3.22/python 3.9...
