### ISSUE TITLE
Petites améliorations de l'interface utilisateur

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#77]
* [x] @WREATCHED Dans les fiches de métadonnées, augmenter la marge entre la bordure haute des groupes et leur contenu pour éviter les labels de groupes à demi recouverts par des widgets.
* [x] @WREATCHED Homogénéisation de l'apparence des widgets de date avec celle des autres widgets : pas de bordure, même icône de flèche pour le menu.
* [x] @WREATCHED (ou @alhyss si nécessite de modifier les SVG) Diminution de la taille des boutons plus et moins.
* [x] @alhyss Colorer les icônes principales du menu, pour les rendre plus aisées à identifier.
* [x] @WREATCHED Définir des raccourcis clavier sur les principales actions du menu : ![read](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/general/read.svg) `CTRL+E` ; ![save](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/general/save.svg) `CTRL+S` ; ![translation](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/general/translation.svg) `CTRL+T` ; ![verrou](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/general/verrou.svg) `CTRL+R` (ou autre).
* [x] @WREATCHED Homogénéiser l'apparence des menus de la barre d'outils. À date le menu de l'export est différent des autres (fond plus clair + bordure).
* [x] @WREATCHED Nouvelles couleurs par défaut pour les éléments de l'interface, issues de la nouvelle palette de la charte graphique de l'Etat.

**Comment by WREATCHED** [comment]
Définir des raccourcis clavier sur les principales actions du menu
et **aide dans l'infobulle**

ça fonctionne super bien

![image](https://user-images.githubusercontent.com/66324136/183919933-be74cbb8-ffa6-42b6-a492-ce07ecae155e.png)

**Comment by alhyss** [comment]
Pourquoi il ne veut pas de `Ctrl+S` 😭 ???

`Ctrl+I`, ce n'est pas super pratique puisqu'il faut le faire à deux mains (ou avoir de très grandes mains)...

J'hésite entre deux approches : 
* Soit on prend juste un raccourci confortable pour la sauvegarde, même s'il ne sera pas très intuitif. Genre `Ctrl+D` s'il est dispo.
* Soit on définit tous les raccourcis claviers avec `Ctrl+Shift+` au lieu de `Ctrl+` - sous réserve qu'ils soient tous dispo dans ce cas.

@WREATCHED Tu en penses quoi ?

**Comment by WREATCHED** [comment]
Suite à notre concertation, on mettra Alt+Maj+Lettre
Ex : pour sauvergarder : Alt+Maj+S

**Comment by WREATCHED** [comment]
On pourra pour le copier Alt+Maj+C et le Coller Alt+Maj+V

**Comment by WREATCHED** [comment]
J'ai rajouter vider la fiche de métadonnées avec Alt+Maj+B pour Blank
Tout fonctionne

**Sept raccourcis :**
![image](https://user-images.githubusercontent.com/66324136/183939518-3e9eb54f-8879-49c1-8fee-296bf140ba01.png)

**Comment by WREATCHED** [comment]
Homogénéisation de l'apparence des widgets de date avec celle des autres widgets : pas de bordure, même icône de flèche pour le menu.

![image](https://user-images.githubusercontent.com/66324136/184085305-8ed1acf6-e4a8-4344-93ac-9dc0b2b3a820.png)

Avis ?

**Comment by WREATCHED** [comment]
Et aussi

**Comment by alhyss** [comment]
Pour les dates, le style du bouton de la flèche n'est toujours pas exactement le même que les autres. Il y a un effet pseudo-3D sur celui-là, tes boutons habituels sont en 2D (et plus jolis).

Ok pour les unités de durées ! C'est vrai que c'est plus logique de ne pas pouvoir cliquer sur le texte, considérant que ça ne faisait rien... Est-ce que tu as la possibilité d'ajouter un brin d'espace entre le texte et le bouton ? Est-ce que tu vas faire ça pour tous les boutons similaires (boutons de choix de la langue et boutons de choix de la source) ?

**Comment by WREATCHED** [comment]
Pas si simple

**Comment by alhyss** [comment]
@WREATCHED J'ai poussé les nouvelles icônes. N'hésite pas à critiquer si certaines ne te plaisent pas ! 

Barre des menus : 
![read](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/general/read.svg) ![save](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/general/save.svg) ![translation](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/general/translation.svg)  `fr` ![template](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/general/template.svg) `Mon modèle`
![copy_all](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/general/copy_all.svg) ![paste_all](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/general/paste_all.svg) ![empty](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/general/empty.svg) ![import](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/general/import.svg) ![export](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/general/export.svg) ![configuration](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/general/configuration.svg) ![info](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/general/info.svg) ![verrou](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/general/verrou.svg)

Icônes modifiées du formulaire : 
![plus_button](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/buttons/plus_button.svg) ![minus_button](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/buttons/minus_button.svg) ![source_button](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/buttons/source_button.svg) ![show](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/buttons/geo/show.svg) 

Je dois encore reprendre les autres icônes du bouton d'aide à la saisie des géométrie et celle du bouton de calcul pour remplacer leurs couleurs par celles de la nouvelle palette de la charte graphique, mais ce n'est pas pressé. Dans la même veine, il y aura de la substitution à faire sur les couleurs par défaut pour les groupes de valeurs, groupes de propriétés, etc. Je te dirai.

Autres icônes modifiées : 
![delete](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/general/delete.svg) (pour la suppression des URL de CSW mémorisées)

**Comment by WREATCHED** [comment]
C'est Ok pour moi

**Comment by alhyss** [comment]
@WREATCHED Je t'avais promis de nouvelles couleurs par défaut conformes à la nouvelle [palette de la charte graphique de l'Etat](https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-identite-de-l-etat/couleurs-palette/) : 

```ini
BlocsColor\defaut=#a38e63
BlocsColor\QGroupBox=#a38e63
BlocsColor\QGroupBoxGroupOfProperties=#a38e63
BlocsColor\QGroupBoxGroupOfValues=#465f9d
BlocsColor\QGroupBoxTranslationGroup=#e18b76
BlocsColor\QTabWidget=#cecece
BlocsColor\QLabelBackGround=#e3e3fd
BlocsColor\geomColor=#a38e63
BlocsColor\activeTooltipColorBackground=#fee9e9
```

Globalement, je suis restée dans les mêmes tons : 
- Café `#a38e63` pour les groupes de propriétés et les géométries (je l'ai mis aussi sur `defaut` et `QGroupBox`, comme avant, mais je ne sais pas à quoi ils servent ?).
- Écume `#465f9d` pour les groupes de valeurs.
- Macaron `#e18b76` pour les groupes de traduction.
- Un dérivé du rouge Marianne `#fee9e9` pour l'arrière-plan des infobulles.

Deux différences notables : 
- J'ai mis du gris `#cecece` pour les onglets, car je commençais à trouver qu'il y avait un peu trop de couleurs.
- Pour la même raison (et aussi parce qu'il n'y avait pas de vert d'eau adapté dans la nouvelle palette), je suis partie sur un fond bleuté `#e3e3fd` pour les labels.

Par ailleurs, je trouve que le fond coloré sous les boutons actifs gagnerait aussi à être plus neutre maintenant que les boutons sont de toutes les couleurs. Je propose du gris `#cecece`. Accessoirement, si ce n'est pas trop long à faire, ça pourrait valoir le coup d'en faire aussi un paramètre utilisateur ? Les couleurs qui passent bien en mode jour ne sont pas forcément aussi satisfaisantes en mode nuit ou nuances de gris. Je n'ai pas eu le temps de tester.

**Comment by WREATCHED** [comment]
![Uploading image.png…]()

**Comment by WREATCHED** [comment]
**Boutons actifs**

![image](https://user-images.githubusercontent.com/66324136/184812079-3c0d75af-294a-4ddd-900b-3dd0c758e14d.png)

**Comment by alhyss** [comment]
C'est de plus en plus joli 🤩 !
