### ISSUE TITLE
Espacement vertical dans les fiches de métadonnées

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#79]
Dans les fiches de métadonnées contenant peu d'informations - celles qui n'ont pas de barre de défilement - les widgets sont disposés horizontalement de manière à occuper tout l'espace. Cela se traduit par un espacement démesuré entre les widgets, des QTextEdit exagérément grands, etc. et nuit fortement à la lisibilité des fiches.

![espacement_fiche_metadonnees](https://user-images.githubusercontent.com/55992003/183860140-46a11dd4-a76b-4e43-aae9-009cffbd4f59.png)

La méthode utilisée pour optimiser le placement des widgets dans la barre d'outils pourrait-elle être mise à profit pour améliorer ça ?

**Comment by WREATCHED** [comment]
**RESOLU**
![image](https://user-images.githubusercontent.com/66324136/185919772-12762bb0-c94c-4dc6-9d24-4104f54b17c6.png)

![image](https://user-images.githubusercontent.com/66324136/185919821-8f7c1f6e-7ab7-4fdd-af9b-9779fe6eaf04.png)

**Comment by alhyss** [comment]
C'est parfait ! Bravo @WREATCHED 🥳
