### ISSUE TITLE
Boutons de saisie des géométries

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#8]
Les catégories communes  _Rectangle d'emprise_ (`dcat:bbox`), _Centroïde_ (`dcat:centroid`) et _Géométrie_ (`locn:geometry`) prennent en valeurs des géométries au format WKT (`gsp:wktLiteral`) ou GML (`gsp:gmlLiteral`), soit pas le plus sympathique à saisir à la main...

L'idée serait de s'appuyer sur les fonctionnalités de QGIS pour simplifier la saisie, au moins pour les couches chargées dans QGIS (tout ou partie des options ne seraient pas disponibles pour une ressource sélectionnée dans l'explorateur). Ainsi, on pourrait imaginer un widget annexe `QToolButton`, placé comme d'habitude à droite du `QLineEdit` ou `QTextEdit` et présentant un menu permettant à l'utilisateur de choisir entre plusieurs modes de saisie. Pour les rectangles d'emprises et centroïdes, il pourrait s'agir de `Calculer à partir des données` et `Tracer manuellement`. La catégorie _Géométrie_ supposerait plutôt un tracé manuel ou la copie d'un objet existant.

Côté dictionnaire de widgets, cela se manifesterait par de nouvelles clés internes. Clés de stockage : `'geo widget'`, `'geo menu'` et `'geo actions'`. Clé de paramétrage : `'geo widget type'` (dont la non nullité supposera la création d'un widget d'aide à la saisie des géométries, avec des fonctionnalités associées qui dépendront de la valeur de la clé). La géométrie résultant de l'opération est ensuite simplement rentrée par Plume dans le `QLineEdit` ou `QTextEdit` de la catégorie, et le traitement est ensuite exactement le même que pour toutes les autres catégories de métadonnées.

**Comment by WREATCHED** [comment]
https://user-images.githubusercontent.com/66324136/156880274-db9faa57-da17-48c3-8da7-a7115b6be3f4.mp4

**Comment by WREATCHED** [comment]
https://user-images.githubusercontent.com/66324136/156935096-b6de96ec-6907-4312-a053-f58a342a0c8b.mp4

**Comment by alhyss** [comment]
J'ai mis à jour la documentation technique ([modalités de création de bouton d'aide à la saisie de géométries](https://mtes-mct.github.io/metadata-postgresql/usage/creation_widgets.html#widget-annexe-bouton-d-aide-a-la-saisie-des-geometries) et [description des actions](https://mtes-mct.github.io/metadata-postgresql/usage/outils_saisie_geometries.html)), pour que ce soit davantage en phase avec ce que tu as implémenté.

**Comment by WREATCHED** [comment]
https://user-images.githubusercontent.com/66324136/157879357-b2f6e87b-ffbd-47e2-9f4b-efa593b5cc8f.mp4

**Comment by alhyss** [comment]
Salut @WREATCHED,
Je me répète beaucoup, mais c'est vraiment parfait. Beaucoup mieux que ce que j'imaginais au départ.
Très bonne idée de gérer le zoom sur la géométrie comme un paramètre !
Et je ne vois aucune raison de ne pas diffuser cette version maintenant qu'elle est aussi aboutie, au contraire.

Une question, parce que tu ne l'as pas montré dans tes vidéos : quand les coordonnées mémorisées dans les métadonnées n'utilisent pas le même référentiel que le canevas, tu as pu gérer la conversion ? Et, réciproquement, pour les fonctionnalités de dessin manuel, c'est bien le référentiel du canevas (et pas celui de la couche) qui est déclaré dans les WKT ?

**Comment by WREATCHED** [comment]
https://user-images.githubusercontent.com/66324136/158215750-ea8b6e4b-abcb-437e-bbac-49567634baed.mp4

Toujours du plus

**Comment by WREATCHED** [comment]
Je pensais à qq chose comme une servitude d'un monument historique ou installation classée ou pour déterminer une zone de pollution dans le cadre d'une gestion de crise ......

**Comment by alhyss** [comment]
Quelle est la forme des WKT avec des cercles ? J'ai l'impression qu'il faut passer par du `CIRCULARSTRING` : 
- avec `QgsCircle.toCircularString().asWkt()` pour avoir un WKT correspondant au cercle ;
- avec `QgsCircularString.fromWkt()` pour reconstruire un `QgsCircularString` affichable à partir du WKT pour l'affichage ?

Si c'est ça, alors ma fonction `plume.utils.geomtype_from_wkt` te renverra `'circularstring'` dans ce cas ?

Il y a bien une méthode `QgsCircle.toString`, mais la fonction `ST_GeomFromText` de PostGIS n'arrive pas à interpréter les chaînes qu'elle renvoie. Ça ressemble à ça : `'Circle (Center: Point (0.5 0.5), Radius: 0.70, Azimuth: 45)'`.

**Comment by alhyss** [comment]
C'est implémenté avec : 
- une option d'aide à la saisie `'circle'` supplémentaire pour la clé `'geo tools'`, correspondant à la saisie manuelle d'un cercle ![](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/buttons/geo/circle.svg) et documentée [ici](https://mtes-mct.github.io/metadata-postgresql/usage/outils_saisie_geometries.html#actions-sans-condition-d-activation). Elle est active par défaut sur la propriété de géométrie libre dans les emprises spatiales (`dct:spatial / locn:geometry`) ;
- pour la visualisation, la fonction `plume.utils.geomtype_from_wkt` reconnaît maintenant le type `CIRCULARSTRING`.

Évidemment, je changerai si le type de géométrie n'est pas le bon.

**Comment by WREATCHED** [comment]
Ok

**Comment by alhyss** [comment]
Cool ! C'est rassurant, les polygones qui restent des polygones :)

**Comment by WREATCHED** [comment]
Avec la tronche de travers, bien sûr !!!

**Comment by WREATCHED** [comment]
Pour être certain de ce que l'on souhaite,
Visualisation : reprojection

- sridSource (issu des coordonnées saisies dans l'IHM) **VERS** sridCible (celui du Canvas)

Saisie : reprojection

- Pour la saisie manuelle
  - srid (celui du Canvas)
- Pour la saisie automatique
  - Pour PostgreSQL "bboxpg", "centroidpg"
     - srid (celui du Canvas)
  - Pour le gestionnaire de couche sous Qgis "bboxqgis", "centroidqgis"
     - srid (celui du la couche active)

OK ou KO ?

**Comment by alhyss** [comment]
À la saisie il faut que le référentiel déclaré dans les métadonnées (= fourni en argument à `plume.rdf.utils.wkt_with_srid`) soit celui qui a effectivement été utilisé. À proprement parler il n'y a pas de reprojection, juste la récupération du bon référentiel : 

| Action | Référentiel |
| --- | --- |
|  calcul côté PostgreSQL | celui qui est renvoyé par `plume.pg.queries.query_get_geom_srid` |
|  calcul côté QGIS | celui de la couche |
|  saisie manuelle | celui du canevas |

Et pour la visualisation, oui, l'idée est de projeter dans le référentiel du canevas, sachant que le référentiel source est fourni par `plume.rdf.utils.split_rdf_wkt`.

Bref, ça correspond à ce que tu as écrit, sauf pour les calculs côté PostgreSQL.

**Comment by WREATCHED** [comment]
Bjr Leslie,
Je confirme tout ce que tu as écrit, c'est ce que j'ai implémenté, mais mal traduit par écrit, sniff !!!!

Visualisation : reprojection
- sridSource (issu des coordonnées saisies dans l'IHM) VERS sridCible (celui du Canvas)

Saisie : 
- Pour la saisie manuelle
  - srid (celui du Canvas)
- Pour la saisie automatique
  - Pour PostgreSQL "bboxpg", "centroidpg"
     - srid (celui retourné par `plume.pg.queries.query_get_geom_srid`)
  - Pour Qgis "bboxqgis", "centroidqgis"
     - srid (celui du la couche active)

**Comment by alhyss** [comment]
Alors tout va bien :)

**Comment by WREATCHED** [comment]
Be, il y a du taf, 
Item supplémentaire pour "Cercle", OK
Pb zoom sur le point, normal, pas le même objet, donc je suis dessus, 
Après je regarde deux autres sujets vu hier
Polygon pour polygone au lieu de linestring
circularstring à gérer.
etc...

**Comment by alhyss** [comment]
Peut-être une mauvaise idée, mais est-ce que tu ne pourrais pas juste gérer le zoom à partir du rectangle d'emprise de la géométrie, quelle que soit sa nature ? Toutes les classes de géométries de QGIS ont au moins une méthode `calculateBoundingBox`, non ?

**Comment by WREATCHED** [comment]
J'étais absent une heure,
Non, mais pas de souci, je vais comme d'hab trouver et faire.
Je te tiens informé

**Comment by WREATCHED** [comment]
Ouf 
`  #** -----
  #** Circle
  #** -----
  def showCircle(self, rubberBand, x, y) :
      rubberBand.reset()
      r = sqrt(x.sqrDist(y))
      feature = QgsFeature()
      feature.setAttributes([x, y, r])
      feature.setGeometry(QgsCircle(QgsPoint(x.x(), y.y()), r).toCircularString())
      self.rubberBand.addGeometry(feature.geometry(),None)
      self.rubberBand.show()
      return
  #-----     
  def circle(self):
      pointsCircle = [ QgsPointXY(self.rubberBand.getPoint(0, i)) for i in range(self.rubberBand.numberOfVertices()) ]
      geomCircleString = QgsCircularString()
      equi = len(pointsCircle)/4
      p1, p2, p3, p4, p5 = pointsCircle[int(equi*0)], pointsCircle[int(equi*1)], pointsCircle[int(equi*2)], pointsCircle[int(equi*3)], pointsCircle[int(equi*4) - 1]
      geomCircleString.setPoints([QgsPoint(p1), QgsPoint(p2), QgsPoint(p3), QgsPoint(p4), QgsPoint(p5), QgsPoint(p1)]) 
      return geomCircleString.asWkt()
  #-----
  def showCircle(self, pointsCircle):
      #Instanciation d'une géom QgsCircularString
      geomCircle = QgsCircularString()
      geomCircle.fromWkt(pointsCircle)
      #Lecture de chaque points pour la transformation
      points = geomCircle.points() 
      points = [ transformSourceCibleLayer(self.srid, self.mAuthid, QgsPointXY(p)) for p in points ]
      #Instanciation d'une géom QgsCircularString pour alimenter la géométrie du rubberBand
      feature = QgsFeature()
      geomCircleString = QgsCircularString()
      geomCircleString.setPoints(QgsPoint(p) for p in points)
      feature.setGeometry(geomCircleString)
      self.rubberBand.addGeometry(feature.geometry(),None)
      return 
`
Te fais une vidéo pour conclure, mais c'est plutôt cool maintenant que c'est implémenté

**Comment by WREATCHED** [comment]
https://user-images.githubusercontent.com/66324136/159021340-e883bb81-dea9-4dcd-bd4e-d532853b0930.mp4

Je pense que ça va faire un bon produit à montrer
version=0.2.10

**Comment by alhyss** [comment]
Salut @WREATCHED,

J'ai fait quelques essais avec les géométries, et c'est vraiment chouette :)

Quelques petites remarques tout de même, pour rester fidèle à ma réputation : 
- Est-ce qu'il serait envisageable de désactiver le bouton de visualisation quand il n'y a pas de valeur dans le widget ? Ou a minima, faire en sorte que cliquer sur le bouton n'ait aucun effet dans ce cas (on resterait sur l'oeil ouvert), ce serait peut-être plus logique ? Tu peux dire non, et ce n'est pas urgent dans tous les cas.
- Quand je trace manuellement un point, puis l'affiche, puis calcule le centroïde (sans avoir préalablement désactivé l'affichage), le point manuel disparaît, par contre l’icône reste sur l'oeil fermé comme s'il y avait encore quelque chose d'affiché. Après, tout rentre dans l'ordre - réactiver l'affichage laisse bien l'oeil fermé et il n'y a pas de problème - c'est sans doute juste une commande de rétablissement de l'icône qui manque au moment où tu désactives l'affichage. C'est la même chose si je trace manuellement un rectangle puis calcule le rectangle d'emprise.
- J'ai un plantage sous QGIS 3.16 avec la visualisation des géométries ponctuelles quand le zoom automatique est activé. `QgsVertexMarker.center` n'apparaît qu'en 3.18, apparemment.

```
2022-03-22T08:52:27     WARNING    Traceback (most recent call last):
              File "C:/Users/alhyss/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\plume\bibli_gene_objets.py", line 564, in 
              _mObjetQToolButton.clicked.connect(lambda : action_mObjetQToolButtonGeoToolsShow(self, _mObjetQToolButton, _keyObjet, _valueObjet))
              File "C:/Users/alhyss/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\plume\bibli_gene_objets.py", line 651, in action_mObjetQToolButtonGeoToolsShow
              self.dic_objetMap[__keyObjet] = GeometryMapToolShow(self, __keyObjet, mCanvas, mAuthid, mCoordSaisie, self.dic_geoToolsShow[__keyObjet])
              File "C:/Users/alhyss/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\plume\bibli_plume_tools_map.py", line 339, in __init__
              self.canvas.setExtent(QgsGeometry.fromWkt(self.rubberBand.center().asWkt()).boundingBox())
             AttributeError: 'QgsVertexMarker' object has no attribute 'center'
```

**Comment by alhyss** [comment]
Je clos l'issue. À ce stade, je pense qu'on peut dire que la fonctionnalité est implémentée, et pas qu'à moitié ! S'il y a des bugs ou de petites améliorations à apporter, on pourra les traiter dans de nouvelles issues.
