### ISSUE TITLE
Cadre parasite du `QScrollArea` ?

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#80]
Il reste un cadre surnuméraire quasi superposé avec la bordure intérieure des onglets.

On le voit clairement quand on met une bordure claire aux onglets : 
![cadre_parasite](https://user-images.githubusercontent.com/55992003/184404727-6ac343cd-c2e1-4336-8c44-a7f90f106518.png)

Par contraste, sur l'onglet d'accueil qui n'a pas de `QScrollArea` : 
![pas_de_cadre_parasite](https://user-images.githubusercontent.com/55992003/184406125-0e0ee9d7-5327-4d62-b65b-e6ffd4ae56dd.png)

J'arrive à l'enlever, mais je perds le style de la barre de défilement dans la bataille et me retrouve avec une barre en fausse 3D à la mode Windows XP... Ça ressemble au problème que que tu as avec les `QComboBox`, `QDateEdit`, etc : apparemment, avec ces widgets dès que tu touches à un paramètre et il faut réécrire toute leur feuille de style et ça dépasse ma compréhension quasi nulle du sujet des feuilles de style.

Bref, c'est purement esthétique et pas dramatique, donc - sauf à ce que tu vois une bonne raison de traiter ça prochainement - je ne flèche pas sur la v1. Peut-être qu'il vaut même mieux ne pas y toucher du tout.

**Comment by WREATCHED** [comment]
Résolu

**Comment by alhyss** [comment]
Je savais bien qu'il fallait laisser faire les pro 😄
