### ISSUE TITLE
Visualisation et mode d'utilisation des boutons de géométries

### ISSUE THREAD

**Issue by WREATCHED** [MTES-MCT/metadata-postgresql#81]
Afin d'homogénéiser les boutons de géométries avec les autres boutons, il s'avère nécessaire d'utiliser la méthode "setPopupMode" avec l'enum "DelayedPopup".
Toutefois, le comportement du bouton ne réagit pas comme les autres pour ouvrir le menu dudit bouton.
Il suffit d'appuyée 2 à 3 secondes afin d'ouvrir le menu déroulant spécifiques aux géométries.

Ce fonctionnement demandé uniquement en mode édition est précisé dans l'infobulle

![image](https://user-images.githubusercontent.com/66324136/184850565-9467e511-b854-46ab-bb28-93353cc8cf82.png)

` InstantPopup  MenuButtonPopup DelayedPopup
 _mObjetQToolButton.setToolButtonStyle(Qt.ToolButtonTextBesideIcon)
  _mObjetQToolButton.setStyleSheet("QToolButton {border: none; }")`

**Comment by alhyss** [comment]
Pour mémoire : le choix de `DelayedPopup` vise surtout à maintenir l'homogénéité visuelle des boutons avec menus, qu'ils servent uniquement à ouvrir le menu ou non. Si ce fonctionnement s'avère gêner les utilisateurs, il sera possible d'utiliser pour les boutons avec menu + action directe :
- Soit `MenuButtonPopup`. Cette option est légèrement différente visuellement, puisque la flèche d'ouverture du menu est alors séparée du bouton.
- Soit `InstantPopup`, en ré-intégrant au menu la fonctionnalité gérée directement par le bouton (ici la visualisation des géométries).
