### ISSUE TITLE
Petits ajustements sur les boutons

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#82]
Quelques points à consolider pour les boutons de la barre d'outils et du formulaire : 
- [x] Certains textes des menus apparaissent toujours tronqués sur mes écrans, spécialement celui paramétré avec grossissement à 125%. Concerne au moins les menus du bouton d'export (barre d'outils) et du bouton de sélection de l'unité (formulaire), probablement aussi les menus des boutons de sélection de langue (barre d'outils et formulaire).
- [x] J'ai de légères superpositions entre le texte et la flèche de certains boutons. En fait essentiellement le bouton de sélection de l'unité du formulaire quand `'heures'` est sélectionné, et je crois que ça n'arrive que sur mon écran avec grossissement.
- [x] Faire en sorte que les cadres des boutons n'apparaissent qu'au survol de la souris (faisabilité confirmée par @WREATCHED avec `QToolButton.setAutoRaise`).
- [x] Voir s'il est possible d'utiliser `QAbstractButton.setDown` pour gérer les boutons activables Concerne le bouton d'activation du mode édition, le bouton d'activation du mode traduction et le bouton de verrouillage pour la barre d'outils, ainsi que le bouton de visualisation des géométries pour le formulaire.
Réponse @WREATCHED : 
Possible mais avec la méthode _mObjetQToolButton.**setCheckable**(True) de l'objet QToolButton et la méthode dans les actions _mObjetQToolButton.**setChecked**(True)

**Comment by WREATCHED** [comment]
![image](https://user-images.githubusercontent.com/66324136/185407555-43a60bb0-69a8-4333-b758-0a47713bed5d.png)

**Comment by alhyss** [comment]
Je crois que j'ai trouvé pour les boutons avec des icônes invisibles. Par défaut, le thème fixe une taille commune à toutes les icônes (21 x 21px en pratique dans notre cas), mais on peut la modifier pour un bouton donné. En préservant la hauteur du thème : 

```python
h = button.iconSize().height()
button.setIconSize(QSize(1, h))
```
Il faut remettre `blank.svg` à 1px de large dans ce cas.

J'obtiens : 

![bouton_selection_langue_sans_espace](https://user-images.githubusercontent.com/55992003/185978353-33f2f184-c580-43d7-9003-5ec33e17f690.png)

**Comment by alhyss** [comment]
Pour tout le reste, ça m'a l'air bon !

**Comment by WREATCHED** [comment]
C'est fait, et aussi dans l'IHM

![image](https://user-images.githubusercontent.com/66324136/186080554-9be754e0-418b-46db-92a2-61d1a493da5c.png)

**Comment by WREATCHED** [comment]
Je te pousse une version tout de suite
