### ISSUE TITLE
Ouverture de Plume sur une couche fantôme

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#83]
Deux cas bizarres...

Cas 1 :
1. J'ouvre Plume.
2. Je sélectionne une couche PostgreSQL dans l'explorateur.
3. Ses métadonnées apparaissent normalement dans Plume.
4. Je passe en mode édition.
5. Je ferme Plume.
6. Je sélectionne autre chose qu'une couche PostgreSQL dans l'explorateur.
7. Je rouvre Plume.
8. Attendu : Plume s'ouvre sur l'écran d'accueil. _Réalité : c'est la fiche de métadonnées de la couche sélectionnée au 2. qui apparaît._
9. Pour autant que je puisse voir, on peut travailler normalement avec cette fiche. Il n'y a pas d'erreur.

Cas 2 :
1. Je sélectionne une couche PostgreSQL dans l'explorateur.
2. J'ouvre Plume.
3. Les métadonnées de la couche apparaissent normalement.
4. Je passe en mode édition.
5. Je ferme Plume.
6. Sans avoir touché à l'explorateur, je rouvre Plume.
7. Attendu : les métadonnées de la couche (qui est a priori toujours sélectionnée) apparaissent. _Réalité : je vois l'écran d'accueil, mais aucun des boutons de la barre d'outils n'est grisé !_
   ![bizarre_1](https://user-images.githubusercontent.com/55992003/184925268-413bef64-0b11-4571-8527-394f40653008.png)
10. Si je clique sur le bouton d'activation du mode édition (qui aurait dû être grisé), j'ai l'erreur _"La couche active correspondante aux métadonnées dans Plume n'existe plus."_ C'est très bien que ça se règle de cette façon, pas de plantage ni rien, c'est seulement le point précédent qui me paraît anormal.

Je crois que le problème du cas n°2 est apparu avec les dernières modifications sur la barre d'outils, car je n'avais jamais vu ça jusqu'à aujourd'hui, et ce n'est pas faute d'avoir constamment ouvert et fermé Plume ces derniers jours. De mémoire, je dirais que jusqu'ici Plume ne retrouvait pas non plus la couche dans ce cas (peut-être parce que même si la couche est toujours sélectionnée, le panneau Explorateur n'est pas considéré comme actif ?). Mais il affichait un écran d'accueil normal avec boutons désactivés, ce qui est déjà préférable.

Pour le cas n°1, je suis un peu moins sûre. Il est possible que je ne l'aie simplement jamais remarqué.

**Comment by alhyss** [comment]
Au fait, je me suis rendu compte que j'avais omis de pinailler sur ce message d'erreur là.

Actuel : 
![message_erreur_couches](https://user-images.githubusercontent.com/55992003/185073409-9072e5b8-83dd-4c5a-a69f-38ee4d68a575.png)

Je propose de simplifier un peu le message : 
_La couche décrite par les métadonnées n'existe plus. Pour continuer, sélectionnez sur une nouvelle couche dans le panneau des couches ou l'explorateur de QGIS._

(a minima, il faut enlever le "e" en trop à "correspondante", c'est un participe présent)

**Comment by WREATCHED** [comment]
Ok pour le message

**Comment by WREATCHED** [comment]
Yes yes **RESOLU** 😅

**Comment by WREATCHED** [comment]
https://user-images.githubusercontent.com/66324136/185111381-7052c7a7-7db5-4fc9-8f8d-ec14ea854079.mp4

**Comment by alhyss** [comment]
Installé, testé, ça m'a l'air en parfait ordre ! 🥳
