### ISSUE TITLE
Suppression de l'ensemble des PNG

### ISSUE THREAD

**Issue by WREATCHED** [MTES-MCT/metadata-postgresql#84]
De façon historique, les images de l'interface de Plume cohabitent sous deux formats : SVG et PNG.
Il serait cohérent de faire en sorte de n'avoir, sauf exception pour des raisons techniques, que des images au format SVG.
@alhyss 
- [x] Refaire les formats PNG existant au format SVG en gardant les mêmes noms (sauf exception les renommer de façon logique), je pense par exemple au source_button.svg et source_button.png qui n'ont rien à voir (renommer dans ce cas source_button.png en button_select.svg).

@WREATCHED 
- [x] Parcourir l'ensemble du code de Plume et faire les modifications nécessaires pour n'utiliser que les SVG

**Comment by alhyss** [comment]
Pour ce qui est à refaire vs jeter, ma première impression à la seule vue de l'interface.

Probablement à refaire : 
- `buttons/source_button.png`. Est-ce qu'on le garde le logo de Plume ici, ou est-ce que j'en profite pour faire une petite flèche ou coche un peu plus sobre (je pencherais plus pour ça, mais comme tu veux @WREATCHED) ? Si on garde le logo de Plume, est-ce qu'il t'est possible d'utiliser directement `logo/plume.svg` ou est-ce que les dimensions posent problème ? Autant que possible, je préfèrerais ne pas dupliquer le fichier. S'il y a un SVG spécifique, je le nommerai `selected.svg`. Il n'est pas censé exclusivement servir pour le menu des sources.
- `buttons/dropDownArrow.png` et `buttons/dropDownArrowGeo.png` ? Si je comprends, le premier sert pour les QComboBox, QDateEdit, etc., et le second pour les boutons avec menu ?
- `buttons/vierge.png` ?? Pas de problème pour te faire un SVG vide de 70x70 px, mais à quoi il sert exactement, celui-là ?

Probablement à jeter : 
- `general/about.png` et `general/assistance.png`. Seul `general/info.svg` est utilisé pour l'icône de la barre d'outils. On pourrait ajouter des icônes dans le menu, mais ça ne paraît pas crucial.
- `general/corbeille.png` et `general/corbeille.svg`. C'est `general/delete.svg` qui sert pour la suppression des URL de CSW mémorisés.
- `general/erreur_normale_postmeta.png`. C'est une image d'AsgardManager, elle n'est plus utilisée pour les messages d'erreur sauf erreur de ma part.
- Tous les PNG du dossier `logo/`, sauf `logo/logoabout2.png`. Cette image-là va rester un PNG puisque c'est supposé être une capture d'écran, il faudra juste l'actualiser quand tu auras fini de travailler sur l'interface. Et peut-être changer le nom en quelque chose d'un peu plus explicite, genre `ui_screenshot.png` ? Je me dis aussi qu'il vaudrait mieux un dossier à part pour les image de l'à propos, même s'il n'en reste qu'une à ce stade. Je pars du principe - à confirmer - que `logo/plume.svg` peut être utilisé à la place de tous les autres PNG.

**Comment by alhyss** [comment]
Pour les nouveaux SVG.

Je t'ai fait un SVG en remplacement de `buttons/dropDownArrow.png` : `buttons/drop_down_arrow.svg`.
![drop_down_arrow](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/buttons/drop_down_arrow.svg)
En pratique, il est (volontairement) légèrement plus discret que les boutons d'origine. Si ça te semble contestable, je peux sans difficulté ajuster les dimensions ou les couleurs.

`buttons/selected_blue.svg` ![selected_blue](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/buttons/selected_blue.svg) est la petite flèche servant à identifier l'item sélectionné dans les menus des boutons du formulaire (boutons de sélection de la source, de la langue et de l'unité).

`general/selected_brown.svg` ![selected_brown](https://raw.githubusercontent.com/MTES-MCT/metadata-postgresql/main/plume/icons/general/selected_brown.svg) est une variante du précédent avec des tons bruns au lieu de bleus. Elle a vocation à servir pour les menus des boutons de la barre d'outils (choix du modèle et choix de la langue principale).

Il n'y en avait pas d'autre à faire au final, si ?

**Comment by WREATCHED** [comment]
Grrrr !!! : changement de nom du png. du coup j'ai cru que ça ne fonctionnait pas avec les styleSheet

Ne reste comme convenu qu'un seul png
![image](https://user-images.githubusercontent.com/66324136/185362540-8d91e6aa-208d-4d56-94b5-30cbc3ca08a8.png)
