### ISSUE TITLE
Installation Plugin QGIS V0.5 Bêta

### ISSUE THREAD

**Issue by CBT-DRAAF** [MTES-MCT/metadata-postgresql#86]
Bonjour,

Je travaille à la DRAAF ARA avec Michaël Delorme.

A l'occasion du changement de serveur de notre base base Postgres. Nous avons décidé d'utiliser la suite ASGARD et l'outil PLUME.

J'ai essayé ce matin d'installer le plugin Plume pour QGIS et cela n'a pas fonctionné. (L'extension Plume est déjà installée sur le serveur Postgres)

Je travaille avec la version 3.16.14 standard de QGIS (Ce n'est pas la version packagée du MTES/MCT qui ne fonctionne pas avec l'outil d'installation WAPT utilisé par notre service informatique). J'ai récupéré le plugin le site Github (V0.5 Bêta)

Voici le message d'erreurs : 
---------------------------------
Impossible de charger l'extension 'plume' provoque une erreur lors de l'appel à sa méthode classFactory()

ModuleNotFoundError: No module named 'rdflib'

Traceback (most recent call last):
  File "c:\PROGRA~1/QGIS31~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/c.berthier-tuaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\plume\__init__.py", line 5, in classFactory
    from .plume import MainPlugin
  File "c:\PROGRA~1/QGIS31~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/c.berthier-tuaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\plume\plume.py",line 37, in
    from . import doplume_ui
  File "c:\PROGRA~1/QGIS31~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/c.berthier-tuaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\plume\doplume_ui.py", line 10, in
    from .plume_ui import Ui_Dialog_plume
  File "c:\PROGRA~1/QGIS31~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/c.berthier-tuaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\plume\plume_ui.py", line 17, in
    from . import bibli_plume
  File "c:\PROGRA~1/QGIS31~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/c.berthier-tuaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\plume\bibli_plume.py", line 20, in
    from plume.rdf.widgetsdict import WidgetsDict
  File "c:\PROGRA~1/QGIS31~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/c.berthier-tuaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\plume\rdf\widgetsdict.py",line 19, in
    from plume.rdf.rdflib import Literal, URIRef, BNode
  File "c:\PROGRA~1/QGIS31~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/c.berthier-tuaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\plume\rdf\rdflib.py", line 20, in
    from rdflib.graph import Graph
  File "c:\PROGRA~1/QGIS31~1.14/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'rdflib'

Version de Python : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
Version de QGIS : 3.16.14-Hannover Hannover, 42791986

Chemin Python :

·                     C:\Users/c.berthier-tuaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\uniquesvaluesalgo

·                     C:\Users/c.berthier-tuaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\thematic

·                     c:/PROGRA~1/QGIS31~1.14/apps/qgis-ltr/./python

·                     C:/Users/c.berthier-tuaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python

·                     C:/Users/c.berthier-tuaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins

·                     c:/PROGRA~1/QGIS31~1.14/apps/qgis-ltr/./python/plugins

·                     C:\Program Files\QGIS 3.16.14\bin\python39.zip

·                     c:\PROGRA~1\QGIS31~1.14\apps\Python39\DLLs

·                     c:\PROGRA~1\QGIS31~1.14\apps\Python39\lib

·                     C:\Program Files\QGIS 3.16.14\bin

·                     c:\PROGRA~1\QGIS31~1.14\apps\Python39

·                     c:\PROGRA~1\QGIS31~1.14\apps\Python39\lib\site-packages

·                     c:\PROGRA~1\QGIS31~1.14\apps\Python39\lib\site-packages\GDAL-3.4.0-py3.9-win-amd64.egg

·                     c:\PROGRA~1\QGIS31~1.14\apps\Python39\lib\site-packages\win32

·                     c:\PROGRA~1\QGIS31~1.14\apps\Python39\lib\site-packages\win32\lib

·                     c:\PROGRA~1\QGIS31~1.14\apps\Python39\lib\site-packages\Pythonwin

·                     C:/Users/c.berthier-tuaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python

·                     C:\Users\c.berthier-tuaz\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools

·                     C:\Users\c.berthier-tuaz\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools

·                     C:\Users/c.berthier-tuaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2streetview

·                     C:\Users\c.berthier-tuaz\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\go2streetview\res

·                     C:\Users\c.berthier-tuaz\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms

·                     C:\Users/c.berthier-tuaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing

·                     C:\Users\c.berthier-tuaz\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing

             C:\Users\c.berthier-tuaz\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs
-------------------

Je vous remercie de m'indiquer quelles erreurs j'ai commises et comment faire fonctionner cette application

**Comment by CBT-DRAAF** [comment]
Merci beaucoup !
 J'ai suivi votre manipulation et tout fonctionne désormais sur mon poste. Effectivement, il y a eu plusieurs versions concurrente de QGIS sur mon PC et le ménage n'avait pas été fait correctement (Comme nous ne sommes plus administrateur de nos postes, cela pose parfois des problèmes lors des mises à jour de logiciels ... :-(  )

**Comment by alhyss** [comment]
C'est parfait ! Désolée que vous ayez été confrontée au problème, ça confirme qu'il y avait urgence à le corriger.
