### ISSUE TITLE
Sécurisation du changement de la langue et/ou du modèle

### ISSUE THREAD

**Issue by WREATCHED** [MTES-MCT/metadata-postgresql#88]
Il s'agit d'avertir l'utilisateur lorsqu'il change de langue et ou de modèle.
Afficher le message identique à celui pour le mode édition et le mode traduction comme le montre l'image ci-dessous.
![image](https://user-images.githubusercontent.com/66324136/186187089-8991e76f-451d-4205-a372-f79755221700.png)

**Comment by WREATCHED** [comment]
**RESOLU**
Version poussée sur le Git

**Comment by alhyss** [comment]
Ah tiens, il faudrait renommer le paramètre qui contrôle l'activation des avertissements.

Libellé : _Avertir de la perte des informations non sauvegardées lors des changements de mode_
Infobulle : _Quitter le mode édition, activer ou désactiver le mode traduction, changer la langue principale de saisie et changer le modèle sont des actions qui provoquent la réinitialisation de la fiche de métadonnées selon la dernière sauvegarde. Lorsque cette case est cochée, Plume vous alerte si vous réalisez l'une de ces opérations sans avoir préalablement enregistré vos modifications._

**Comment by WREATCHED** [comment]
**Réponse**
![image](https://user-images.githubusercontent.com/66324136/186622802-669bb92f-6402-4133-8371-82305639cbe4.png)
