### ISSUE TITLE
Réorganisation des onglets de la boîte de paramétrage

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#90]
Je me demande si ça ne vaudrait pas le coup de réorganiser un peu la boîte de personnalisation de l'interface ? Ça nous faciliterait la vie pour la documentation et aiderait peut-être l'utilisateur à s'y retrouver.

Mon idée serait de davantage séparer les paramètres qui concernent des parties différentes de l'interface.

Une première proposition pour discussion :
- onglet `Général` pour : 
    - le choix du type d'interface (panneau, etc.)
    - le choix de la police, puisqu'elle affecte à la fois les fiches de métadonnées et la barre de menu
    - l'activation des avertissements à la sortie du mode édition etc.
- onglet `Fiches de métadonnées` pour tout ce qui reste dans l'actuel onglet "Apparence" sauf le cadre "Explorateur".
- onglet `Géométries` pour l'actuel onglet "Apparence des géométries"
- onglet `Explorateur` pour le contenu du cadre "Explorateur" de l'actuel onglet "Apparence"
- onglet `Avancé` pour tout ce qui reste dans l'actuel onglet "Paramètres avancés"

**Comment by WREATCHED** [comment]
**Maquette pour avis et validation**
![image](https://user-images.githubusercontent.com/66324136/186663722-eaa43689-da2b-4ad9-a703-f01af5d8ce8d.png)

**Comment by alhyss** [comment]
C'est ce que bien j'avais en tête pour la répartition :)

Pour les labels, est-ce que plutôt que d'étirer le `QLabel` ce serait possible d'autoriser le texte à se mettre sur plusieurs lignes et laisser le widget gérer tout seul sa hauteur (comme tu l'as fait pour les métadonnées textuelles en lecture seule dans les fiches) ?

Sinon, dans l'onglet "Explorateur", ce serait bien que "Modification de l'infobulle" soit clairement en premier, vu qu'il conditionne tout le reste.

**Comment by WREATCHED** [comment]
**REPONSE**
![image](https://user-images.githubusercontent.com/66324136/187893679-3b5c523e-3d44-4d25-b24c-6b801cafc647.png)
