### ISSUE TITLE
Textes tronqués dans la boîte de paramétrage

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#91]
J'ai beaucoup de textes tronqués dans la boîte de paramétrage sur mon écran avec un grossissement à 125%. Ci-après quelques exemples, j'imagine qu'il y en aurait plus à 150%, car tu dois figer quasi toutes les dimensions actuellement. Ça concerne des `QLabel`, des étiquettes de boutons, des noms d'onglets...

_Explorateur_ à 125%
![parametres_textes_tronques_explorateur](https://user-images.githubusercontent.com/55992003/186623511-5831fc7e-7b4d-4315-a0e0-0d6adcb774a9.png)

_Apparence des géométries_ à 125%
![parametres_textes_tronques_geometries](https://user-images.githubusercontent.com/55992003/186623856-04d028a6-c819-48b7-ab9b-f6b4fbc77b6b.png)

_Paramètres avancés_ à 125%
![parametres_textes_tronques_avance](https://user-images.githubusercontent.com/55992003/186624067-ace97786-a39e-4eae-af83-b3d956ea90c9.png)

**Comment by WREATCHED** [comment]
En cours
![image](https://user-images.githubusercontent.com/66324136/186847369-a954fabc-e3e3-4c55-a3d7-ab723d2915fd.png)
