### ISSUE TITLE
Fonctionnalités manquantes pour un rôle non propriétaire de la table

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#94]
Lorsqu'on ouvre une fiche de métadonnées avec un rôle qui n'est pas propriétaire de la table ou vue considérée, et n'est donc pas habilité à modifier les métadonnées, tous les boutons de la barre d'outils sont désactivées à l'exception des boutons de paramétrage, d'aide et de verrouillage.

![fonctionnalites_manquantes_role_non_proprietaire](https://user-images.githubusercontent.com/55992003/194262865-e40bf0ec-a1c2-4934-96f1-c9cc57c174cc.png)

Il est bien sûr normal que le bouton de bascule en mode édition ne soit pas activable, par contre toutes les autres fonctionnalités habituellement offertes par le mode lecture devraient être disponibles : choix de la langue, choix du modèle, export et copie.

À titre de référence, [cette partie de la documentation technique](https://mtes-mct.github.io/metadata-postgresql/usage/actions_generales.html#caracteristiques-du-bouton) expliquait dans quel cas désactiver le bouton de bascule en mode édition (ce qui fonctionne, donc, mais s'applique actuellement à trop de boutons).

@WREATCHED Est-ce que tu pourras en profiter pour faire une capture de la barre d'outils vue par un rôle non propriétaire, pour ajouter à la partie _Activation et désactivation du mode édition_ de la doc ?

**Comment by WREATCHED** [comment]
**Réponse**
