### ISSUE TITLE
Boite de dialogue d'import des métadonnées

### ISSUE THREAD

**Issue by WREATCHED** [MTES-MCT/metadata-postgresql#95]
**Demande interne (Leslie)**
On suppose que les services souhaiteraient dans la liste des url CSW de pouvoir saisir un libellé explicite en complément de l'url .
Il s'agit donc de pouvoir le saisir et qu'il s'insère dans les mécanismes du QTreeWidget notamment ajout, suppression, glisser/déposer.

**Comment by WREATCHED** [comment]
![image](https://user-images.githubusercontent.com/66324136/195388956-1fa8e7c0-69e3-4966-905f-19c42f3903fe.png)

**Comment by WREATCHED** [comment]
**En vidéo**

https://user-images.githubusercontent.com/66324136/195390904-6a503fee-631c-4418-a68d-43881628b58f.mp4

**Comment by WREATCHED** [comment]
Poussé sur le git

**Comment by alhyss** [comment]
C'est super tout ça ! 😃 

Dans le genre micro-détail, est-ce que maintenant qu'on a deux colonnes dans le tableau on pourrait imaginer écrire au dessus _"CSW mémorisés"_ - par exemple en tant qu'étiquette du `QGroupBox` - et nommer les colonnes _"Libellé"_ (avec une majuscule) et _"URL_" ?

Sinon, est-ce que ton contrôle d'unicité n'oblige pas à supprimer et recréer le CSW quand on veut changer uniquement le libellé ? J'ai tendance à penser que le comportement auquel l'utilisateur s'attend est le suivant : 
- Quand il change le libellé du CSW à URL constante, le libellé de l'enregistrement CSW est mis à jour.
- Quand il change l'URL du CSW à libellé constant, le libellé est mis à jour.

Si tu utilises deux listes distinctes pour gérer les URL et les libellés, ça doit ressembler à ça : 
```python
def update_csw(url_list, label_list, new_url, new_label):
    if not new_url and not new_label:
        return
    csw_index_from_url = url_list.index(new_url) if new_url and new_url in url_list else None
    csw_index_from_label = label_list.index(new_label) if new_label and new_label in label_list else None
    if csw_index_from_url is not None and csw_index_from_label is not None:
        # le libellé et l'URL sont déjà répertoriés, et pas pour le même CSW :
        # on ne garde qu'un CSW avec lesdits libellé et URL
        if csw_index_from_url != csw_index_from_label:
            del url_list[csw_index_from_label]
            del label_list[csw_index_from_label]
            csw_index_from_url = url_list.index(new_url)
            label_list[csw_index_from_url] = new_label
        # si le libellé et l'URL étaient déjà répertoriés pour le même CSW,
        # c'est que rien n'a été modifié, donc il n'y a rien à faire
    elif csw_index_from_url is not None:
        # l'URL est déjà répertoriée, on met à jour le libellé
        label_list[csw_index_from_url] = new_label
    elif csw_index_from_label is not None:
        # le libellé est déjà répertorié, on met à jour l'URL
        url_list[csw_index_from_label] = new_url
    else:
        # URL et libellé non répertoriés = nouveau CSW
        url_list.append(new_url)
        label_list.append(new_label)
```

**Comment by alhyss** [comment]
C'est parfait @WREATCHED 

Il y a juste moi qui avais oublié de regarder les intitulés des champs de saisie, et ce serait mieux avec _"Libellé du CSW"_ plutôt que _"Libellé de l'URL du CSW"_ . Ce n'est pas vraiment l'URL qu'on nomme, plutôt le service lui-même. Désolée 😢

**Comment by WREATCHED** [comment]
![image](https://user-images.githubusercontent.com/66324136/195768725-19d78dd0-2c90-4719-9c8f-8e298e03f4ba.png)

Je repousse tout sur le git

**Comment by alhyss** [comment]
Est-ce que tu commences à lancer des fléchettes sur une cible avec ma tête si je dis que ce serait plus clair avec : 
- _"CSW par défaut"_ au lieu de _"URL par défaut"_
- _"Mes CSW"_ au lieu de _"Mes URL"_
- _"Ajouter ou modifier un CSW mémorisé. L'URL et le libellé seront enregistrés dans la section « Mes CSW » du tableau ci-dessus."_ pour l'infobulle du bouton d'enregistrement. (NB : je n'ai pas mis d'espace insécables sur les guillemets)
- Pour l'infobulle du champ de saisie du libellé : _"Si vous souhaitez mémoriser le CSW, vous pouvez associer un libellé à son URL afin de l'identifier plus aisément."_

En parallèle, ce serait bien que lorsque Plume récupère l'URL éventuellement enregistrée dans les métadonnées à l'ouverture de la boîte de dialogue, tu ailles regarder si elle n'est pas dans la liste des CSW mémorisés afin d'afficher le libellé correspondant, le cas échéant. C'est un peu dommage de n'avoir que l'URL.

**Comment by WREATCHED** [comment]
**OUF**

**Comment by alhyss** [comment]
Merci @WREATCHED  🥲
