### ISSUE TITLE
Petits ajustements de forme sur la fenêtre d'à propos

### ISSUE THREAD

**Issue by alhyss** [MTES-MCT/metadata-postgresql#98]
Rendu sur un écran avec grossissement à 150% : 
![a_propos_barre_defilement](https://user-images.githubusercontent.com/55992003/206397302-1a3f7f40-f4fc-4953-8a5a-7fd60023cf6f.png)

C'est vraiment du détail, mais il y aurait peut-être quelques justement à faire pour que ce soit plus lisible lorsque la barre de défilement apparaît... Par exemple mettre les auteurs avec le reste du texte ?

**Comment by WREATCHED** [comment]
Slt,

**Comment by alhyss** [comment]
Non non, absolument pas ! Ce sera pour la version suivante.

**Comment by WREATCHED** [comment]
**Réponse**
![image](https://user-images.githubusercontent.com/66324136/206642522-0808e039-3886-473b-8a55-2c7fa2167b56.png)

**Comment by WREATCHED** [comment]
**Redimensionnement de chaque partie**
![image](https://user-images.githubusercontent.com/66324136/207245109-e6df0605-959f-450d-8bbc-346649247d90.png)
