### ISSUE TITLE
Gestion des modèles

### ISSUE THREAD

**Issue by WREATCHED** [MTES-MCT/metadata-postgresql#99]
Afin de faciliter la création de modèles spécifiques aux besoins de chaque service, il serait souhaite (voir conclusion suite à la présentation au GT PostGIS du 10/12/2022) de développer un assistant dans l'application Plume.

__Liste des besoins pour la gestion des modèles__

| A faire / Ok| Priorité |Contexte | Besoin | Retour | Qui| 
| :--: | :--: | :--: | -- | :--: | :--: | 
| **OK** | 1 |**Ouverture**	de Plume | Requête	des droits pour afficher l’icône dans la barre d’outils pour gérer ou activer la gestion des modèles  <ul><li>En fonction de l’installation de l’extension Plume_pg et des droits idoines</li><li>Genre g_admin et super utilisateur, avoir les droits nécessaires sur les tables de conception de la gestion des modèles</li><ul>| Boolen | LL | 			 			 								 				 				
| **OK** | 1 | **Création** d’une icône | D’un SVG qui te convient | svg | LL | 
| **OK** | 1 | **Création**	d’une icône dans la barre d’outil | Insérer une nouvelle icône dans la première ligne de la barre d’outil Où ? Entre la roue crantée et le ? | code | DL | 
| **OK**| 1 | **Lecture** Affichage des **modèles disponibles** | Requête qui retourne sous forme de liste ou dictionnaire, à voir ce qui 			est plus simple pour nous deux la liste des modèles existants pour chaque modèle existant, les catégories utilisées la liste des catégories (je ferais la diff pour les non utilisées ou directement les non utilisées pour chaque modèle existant, les attributs 				 					<ul><li>Label</li><li>tooltip</li><li>value</li><li>la liste des onglets pour alimenter la QComboBox</li></ul>| Query | LL | 
| **OK**|   |&#8593;| Implémentation dans le plugin  | |DL | 
| **OK**| 1 | **Sauvegarde** (Create and Update) Affichage des modèles disponibles | Description | Query | LL | 
| **OK**|   |&#8593;| Implémentation dans le plugin  | |DL | 
| **OK**| 2 | **Lecture** Liste des **modèles** | Requête qui retourne sous forme de liste ou dictionnaire, à voir ce qui est plus simple pour nous deux la liste des modèles existants pour chaque modèle existant, les attributs des modèles <ul><li>Label</li><li>tooltip</li><li>value</li></ul>| Query | LL | 
| **OK**|   |&#8593;| Implémentation dans le plugin  | |DL | 
| **OK**| 2 | **Sauvegarde**(Create and Update) Liste des modèles | Description | Query | LL | 
| **OK**|   |&#8593;| Implémentation dans le plugin  | |DL | 
| **OK**| 3 | **Lecture** Liste des **métadonnées** (catégories) | Requête qui retourne sous forme de liste ou dictionnaire, à voir ce qui 			est plus simple pour nous deux la liste des métadonnées existantes pour chaque métadonnée existante, les attributs des modèles<ul><li>Label</li><li>tooltip</li><li>value</li></ul>| Query | LL | 
| **OK**| 3 |&#8593;| Implémentation dans le plugin  | |DL | 
| **OK**| 3 | **Sauvegarde** (Create and Update) Liste des métadonnées | Description | Query | LL | 
| **OK**|   |&#8593;| Implémentation dans le plugin  | |DL | 
| **OK**| 4 | **Lecture** Liste des **onglets** (catégories) | Requête qui retourne sous forme de liste ou dictionnaire, à voir ce qui 			est plus simple pour nous deux la liste des onglets existants pour chaque onglet existant, les attributs des  onglets<ul><li>Label</li><li>tooltip</li><li>value</li></ul> | Query | LL | 
| **OK**| 4  |&#8593;| Implémentation dans le plugin  | |DL | 
| **OK**| 4 |**Sauvegarde** (Create and Update) Liste des onglets | Description | Query | LL | 
| **OK**| 4 |&#8593;| Implémentation dans le plugin  | |DL |

**Comment by alhyss** [comment]
@WREATCHED Normalement ça devrait être bon pour les fonctions de lecture. Avec un `fetchall` sur le résultat de la requête, tu auras toujours une liste de tuples, mais chaque tuple contient un unique dictionnaire dont les clés sont les noms des champs de la table.

Quelque chose de cette forme : 
```python
[
    (
        {
            'tab': 'Onglet n°1',
            'tab_num': 1
        }
    ),
    (
        {
            'tab': 'Onglet n°2',
            'tab_num': 2
        }
    )
]
```

**Comment by WREATCHED** [comment]
[2 - CGDD_CD_Note_Campagne_CD_ 2023_0.pdf](https://github.com/MTES-MCT/metadata-postgresql/files/10361525/2.-.CGDD_CD_Note_Campagne_CD_.2023_0.pdf)
[2 - CGDD_CD_Procedure_Candidature.pdf](https://github.com/MTES-MCT/metadata-postgresql/files/10361527/2.-.CGDD_CD_Procedure_Candidature.pdf)
[2 - CGDD_CD_Schema_Processus_Evaluation.pdf](https://github.com/MTES-MCT/metadata-postgresql/files/10361528/2.-.CGDD_CD_Schema_Processus_Evaluation.pdf)
[2 - CD_Thesaurus.xls](https://github.com/MTES-MCT/metadata-postgresql/files/10361529/2.-.CD_Thesaurus.xls)
[2 - CGDD_CD_Calendrier_2023_29092022.pdf](https://github.com/MTES-MCT/metadata-postgresql/files/10361530/2.-.CGDD_CD_Calendrier_2023_29092022.pdf)

**Comment by WREATCHED** [comment]
**Pour traçabilité sur la gestion des catégories non utilisées et des catégories utilisées**

- **DL** --> **LL**
Suite à notre discussion hier soir :
Le soucis est que dans mes Cat IN :
['dct:conformsTo', 1, False]
['dct:created', 1, False]
['dct:description', 1, False]
['dct:modified', 1, False]
['dct:title', 1, False]

Comme tu peux le constater dans cet exemple ['dct:conformsTo', 1, False] est à False pour is_node, donc je ne peux pas le récupérer dans cette condition pour les Cat OUT
La question est : Est-ce normal ?


- **LL** --> **DL**
C'est normal, même si ça ne nous arrange pas... Je pensais que j'avais mis is_node à True pour les classes BlankNode et BlankNodeOrIri (quand la catégorie est un groupe en "mode manuel" mais peut aussi recevoir directement une valeur), mais en fait c'est seulement pour la première. Et c'est un sujet important de toute façon, parce que dans ton arborescence ces catégories seront des groupes, mais il faudra aussi leur afficher un formulaire complet. Un petit message pour expliquer à l'utilisateur le principe pourra d'ailleurs aider.
Mais donc ça veut dire que is_node ne permet pas de repérer les groupes.

Ce n'est sans doute pas du tout comme ça que tu comptais procéder, mais - pour faire (relativement) simple - je te suggère d'appliquer cette méthode pour constituer tes deux listes CategoryIn et CategoryOut :
- Tu boucles sur la liste complète des catégories, triée par ordre alphabétique.
- Pour chaque catégorie, tu commences par regarder dans la table d'association modèle-catégories si elle est utilisée ou non.
- Si elle ne l'est pas et que is_node vaut True, tu ignores la catégorie.
- Sinon, tu éclates le chemin de la catégorie. À toute fin utile, de mon côté j'utilise path_elements = re.split(r'\s*[/]\s*', path) pour découper le chemin, puis paths = [ ' / '.join(path_elements[:i + 1] ) for i in range(len(path_elements) - 1) ] pour en déduire les chemins de tous les ancêtres.
- Si la catégorie est utilisée, tu boucles sur la liste de ses ancêtres. S'ils sont déjà présents dans ton arbre CategoryIn, ok. Sinon, tu les ajoutes avec les informations issues de la table d'association si elles y sont référencées, sinon avec les informations minimales issues seulement de la table des catégories. Ensuite tu ajoutes la catégorie elle-même.
- Si non, tu fais la même chose avec CategoryOut.

Ce fonctionnement a aussi l'intérêt de gérer correctement les cas où des catégories parentes auraient été sauvagement supprimées. Il rend possible les groupes vides, dans le cas où seul le groupe - sans aucun de ses enfants - était inclus dans le modèle. Mais je pense que c'est nécessaire, considérant que l'utilisateur enregistre ses ajouts de catégories un par un. S'il commence par ajouter un groupe, il y aura un moment où l'arbre CategoryIn devra présenter un groupe vide, avant que (en principe) il y ajoute des catégories.

Quand une catégorie bascule de CategoryIn à CategoryOut, rien à faire de particulier côté CategoryIn. Dès lors qu'on admet les groupes vides, cela veut dire qu'on laisse l'utilisateur faire le ménage à la main. Côté CategoryOut, il faut procéder comme lors de l'initialisation de l'arbre : boucler sur les ancêtres de la catégorie à ajouter pour s'assurer qu'ils y sont tous.

Quand une catégorie bascule de CategoryOut à CategoryIn, il faut ajouter les ancêtres d'autant que de besoin côté CategoryIn. Côté CategoryOut, il faut supprimer les groupes vides en bouclant sur la liste des ancêtres triée dans l'ordre inverse - ['a / b', 'a'] au lieu de ['a', 'a  / b'] pour les ancêtres de 'a / b / c', par exemple. Si is_node vaut True et que le groupe n'a plus d'enfant, tu le supprimes.

**Comment by WREATCHED** [comment]
https://user-images.githubusercontent.com/66324136/216618479-1c9725c2-9d2a-4ac3-b132-8b8e0ac57f83.mp4

**Comment by WREATCHED** [comment]
**Avec les chemins complets**



https://user-images.githubusercontent.com/66324136/219092038-da53f9e2-490a-422d-b9ec-d954d01422b3.mp4

**Comment by WREATCHED** [comment]
**Avec le libellé et le nom de la catégorie**


https://user-images.githubusercontent.com/66324136/219092306-e3b98c68-79bc-4a60-8092-e184260b5311.mp4

**Comment by WREATCHED** [comment]
**Avec le nom de la catégorie pour les catégories dites communes et avec le libellé et le nom de la catégorie pour les catégories dites locales**
https://user-images.githubusercontent.com/66324136/219303002-6315c32f-189b-4844-8167-428b1310bf19.mp4

**Comment by WREATCHED** [comment]
https://user-images.githubusercontent.com/66324136/224352886-b6e4bc9d-1feb-4e2b-9dab-061661f950fb.mp4

**Comment by WREATCHED** [comment]
**Résolu**

**Comment by WREATCHED** [comment]
**Corrigé ce jour**

**Comment by WREATCHED** [comment]
Les sauvegardes des catégories utilisées et non utilisées pou un modèle sélectionné

https://user-images.githubusercontent.com/66324136/237055773-a8dd2b5a-c433-4870-bcb2-28473eb97ebc.mp4

**Comment by WREATCHED** [comment]
Nouvelle IHM

**Comment by alhyss** [comment]
C'est vraiment beaucoup plus clair !

Je note qu'il faut une icône pour la réinitialisation.

La seule chose qui m'ennuie un peu, c'est le titre _"choix des métadonnées pour le modèle sélectionné"._ On ne voit pas très bien que c'est le titre de tout ce qui suit... Est-ce que tu peux déjà essayer de mettre une majuscule à _"Choix"_ et l'éloigner un peu de la liste de choix du modèle ?

Pour les infobulles, _"utilisées ou non utilisées"_ et _"associées"_ sont redondants. Que penses-tu de :
- _"Enregistrer la composition du modèle."_
- _"Réinitialiser la composition du modèle."_
- _"Enregistrer la configuration de la métadonnée {catégorie} pour le modèle {modèle}."_ ?

**Comment by WREATCHED** [comment]
OK, je m'y attèle

**Comment by WREATCHED** [comment]
Ton avis![image](https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/3c690b26-cc22-4944-8f2e-00e76ff0bb7b)

**Comment by WREATCHED** [comment]
**Robustesse**

**Comment by WREATCHED** [comment]
- Première version des libellés des propriétés pour 
   - les catégories / modèles
   - les modèles
   - les catégories
   - les onglets

![image](https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/22e7bb52-07d0-4156-8f26-7534c2c616e2)

**Comment by alhyss** [comment]
@WREATCHED Comme convenu, j'ai ajouté quelques petites fonctions pour récupérer les informations qui alimenteront l'aide à la saisie du champ `sources`. Elles sont présentées dans la nouvelle sous-partie [*Champ `source`*](https://mtes-mct.github.io/metadata-postgresql/usage/modeles_de_formulaire.html#champ-sources) de la documentation technique. N'hésite pas si j'ai oublié quelque chose qui te paraîtrait utile.

**Comment by WREATCHED** [comment]
**La vie de Plume continue et son dev aussi**


https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/e58fba78-8dc7-49b6-b492-81c3f3ad9678

**Comment by WREATCHED** [comment]
LECLERC Didier @didier.leclerc
16:46
@Leslie / Didier

Suite aux échanges - mettre l'aide dans la boite d'assistance quand le QWidget a setEnabled(False)

**Comment by WREATCHED** [comment]
https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/6c46c6e2-8de9-4f34-af50-d2ed4f1b9f31

**Comment by WREATCHED** [comment]
https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/6e0ba59d-2044-4574-a17d-9fb684e86ec9

**Comment by WREATCHED** [comment]
**Fin de semaine**
https://github.com/MTES-MCT/metadata-postgresql/assets/66324136/e0b56b7b-f951-4a54-acf1-1946576761fa
